// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: aiming-2-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Aiming2Line({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M20 12a8 8 0 0 1-8 8m8-8a8 8 0 0 0-8-8m8 8h1m-9 8a8 8 0 0 1-8-8m8 8v1m-8-9a8 8 0 0 1 8-8m-8 8H3m9-8V3m3 9a3 3 0 1 1-6 0a3 3 0 0 1 6 0Z"
      />
    </Svg>
  );
}
