// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: alert-octagon-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function AlertOctagonLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M12 7v6m0 3h.002M3.5 9.308v5.384a2 2 0 0 0 .586 1.415l3.807 3.807a2 2 0 0 0 1.415.586h5.384a2 2 0 0 0 1.415-.586l3.807-3.807a2 2 0 0 0 .586-1.415V9.308a2 2 0 0 0-.586-1.415l-3.807-3.807a2 2 0 0 0-1.415-.586H9.308a2 2 0 0 0-1.415.586L4.086 7.893A2 2 0 0 0 3.5 9.308Z"
      />
    </Svg>
  );
}
