// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: american-football-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function AmericanFootballFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M12 20c.946 0 1.788.438 2.338 1.122c-.723.5-1.546.878-2.338.878c-.793 0-1.616-.378-2.339-.878A3 3 0 0 1 12 20m3.842-15.802q.361.388.701.83C17.897 6.79 19 9.25 19 12s-1.103 5.209-2.457 6.973q-.34.44-.701.828A4.99 4.99 0 0 0 12 18a4.99 4.99 0 0 0-3.843 1.8q-.361-.387-.7-.827C6.103 17.209 5 14.75 5 12s1.103-5.209 2.457-6.973q.339-.44.7-.829A4.99 4.99 0 0 0 12 6a4.99 4.99 0 0 0 3.842-1.802M12 8a1 1 0 0 0-1 1a1 1 0 1 0 0 2v2a1 1 0 1 0 0 2a1 1 0 1 0 2 0a1 1 0 1 0 0-2v-2a1 1 0 1 0 0-2a1 1 0 0 0-1-1m0-6c.792 0 1.615.378 2.338.877a2.993 2.993 0 0 1-4.677 0C10.384 2.377 11.208 2 12 2"
      />
    </Svg>
  );
}
