// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: android-2-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Android2Fill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M5.553 4.106a1 1 0 0 1 1.341.447L8.028 6.82A10 10 0 0 1 12 6c1.411 0 2.755.292 3.972.82l1.134-2.267a1 1 0 1 1 1.788.894l-1.174 2.35A9.99 9.99 0 0 1 22 16v1a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2v-1a9.99 9.99 0 0 1 4.28-8.204L5.106 5.447a1 1 0 0 1 .447-1.341M6 13.5a1.5 1.5 0 1 1 3 0a1.5 1.5 0 0 1-3 0m9 0a1.5 1.5 0 1 1 3 0a1.5 1.5 0 0 1-3 0"
        clipRule="evenodd"
      />
    </Svg>
  );
}
