// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: angry-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function AngryLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M9.354 15c.705-.622 1.632-1 2.646-1s1.94.378 2.646 1M8 9l2 1m6-1l-2 1m7 2a9 9 0 1 1-18 0a9 9 0 0 1 18 0Z"
      />
    </Svg>
  );
}
