// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: announcement-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function AnnouncementLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeWidth="2"
        d="M18 9.268a2 2 0 1 1 0 3.465M9 7v11.29a1.71 1.71 0 0 1-3.354.47L4 13m10.907 3.68L17.2 18.4a.5.5 0 0 0 .8-.4V3.87a.5.5 0 0 0-.752-.431l-2.752 1.605A12 12 0 0 1 9.115 6.66l-2.62.146a3.7 3.7 0 0 0 0 7.388l1.877.104a12 12 0 0 1 6.535 2.382Z"
      />
    </Svg>
  );
}
