// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: arrow-right-up-circle-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function ArrowRightUpCircleFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12S6.477 2 12 2m-1.996 5.997a1 1 0 0 0 0 2h2.585l-4.296 4.296a1 1 0 1 0 1.414 1.414l4.297-4.297v2.587a1 1 0 1 0 2 0v-5a1 1 0 0 0-1-1z"
      />
    </Svg>
  );
}
