// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: attachment-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function AttachmentLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="m12.877 4.308l6.54 6.54a5.25 5.25 0 0 1-7.424 7.425l-7.954-7.954a3.501 3.501 0 1 1 4.952-4.952l7.953 7.953a1.751 1.751 0 1 1-2.477 2.477L7.22 8.55"
      />
    </Svg>
  );
}
