// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: attachment-2-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Attachment2Line({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="m5.282 11.647l-.353-.354a4.5 4.5 0 1 1 6.364-6.364l7.778 7.778a4.5 4.5 0 0 1-6.364 6.365l-4.066-4.066a2.25 2.25 0 0 1 3.182-3.182l3.713 3.712"
      />
    </Svg>
  );
}
