// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: attachment-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function AttachmentFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="3"
        d="m12.707 4.221l7.071 7.072a6 6 0 1 1-8.485 8.485l-8.485-8.485a4 4 0 1 1 5.656-5.657l8.132 8.131a2 2 0 1 1-2.828 2.829L6.343 9.17"
      />
    </Svg>
  );
}
