// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: backpack-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function BackpackFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M12 2a4 4 0 0 1 3.893 3.08A5 5 0 0 1 20 10v9a3 3 0 0 1-3 3H7a3 3 0 0 1-3-3v-9a5 5 0 0 1 4.106-4.92A4 4 0 0 1 12 2M9 20h6v-2H9zm1-6a1 1 0 0 0-1 1v1h6v-1a1 1 0 0 0-1-1zm1-5a1 1 0 1 0 0 2h2a1 1 0 1 0 0-2zm1-5c-.74 0-1.384.403-1.73 1h3.46c-.346-.597-.99-1-1.73-1"
      />
    </Svg>
  );
}
