// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: background-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function BackgroundFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="3"
        d="M20 5L4 19m8.714-14L4 12.625M6.429 5L4 7.125m16 4.25L11.286 19M20 17.25L18 19"
      />
    </Svg>
  );
}
