// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: barbell-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function BarbellFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M2 13a4 4 0 0 0 3.14 3.907A3 3 0 0 0 8 19a2 2 0 0 0 2-2v-4h4v4a2 2 0 0 0 2 2c1.34 0 2.476-.88 2.86-2.093A4 4 0 0 0 22 13v-2a4 4 0 0 0-3.14-3.907A3 3 0 0 0 16 5a2 2 0 0 0-2 2v4h-4V7a2 2 0 0 0-2-2c-1.34 0-2.476.88-2.86 2.093A4 4 0 0 0 2 11z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
