// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: bath-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function BathFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        d="M9 3a2 2 0 0 1 2 2v1a1 1 0 1 1-2 0V5H8a1 1 0 0 0-1 1v5h13a2 2 0 0 1 2 2v1a5.99 5.99 0 0 1-2.625 4.96l.332.333a1 1 0 1 1-1.414 1.414l-.877-.877c-.454.11-.928.17-1.416.17H8c-.488 0-.963-.06-1.417-.17l-.876.877a1 1 0 1 1-1.414-1.414l.331-.332A6 6 0 0 1 2 14v-1a2 2 0 0 1 2-2h1V6a3 3 0 0 1 3-3z"
      />
    </Svg>
  );
}
