// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: battery-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function BatteryLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeWidth="2"
        d="M3 8a1 1 0 0 1 1-1h13a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1zm15 2h1a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-1z"
      />
    </Svg>
  );
}
