// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: beachball-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function BeachballLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeWidth="2"
        d="M12 12a4.5 4.5 0 1 0-6.364-6.364M12 12a4.5 4.5 0 0 0 6.364 6.364M12 12a4.5 4.5 0 1 0-6.364 6.364M12 12a4.5 4.5 0 0 0 6.364-6.364M21 12a9 9 0 1 1-18 0a9 9 0 0 1 18 0Z"
      />
    </Svg>
  );
}
