// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: bed-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function BedLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M3 6v12m0-4h18m0 0v4m0-4v-4a2 2 0 0 0-2-2h-7v6M9 9.5a1.5 1.5 0 1 1-3 0a1.5 1.5 0 0 1 3 0"
      />
    </Svg>
  );
}
