// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: bilibili-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function BilibiliLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M7.832 3.445a1 1 0 0 0-1.664 1.11L7 4zm10 1.11a1 1 0 0 0-1.664-1.11L17 4zM10 12a1 1 0 1 0-2 0zm-2 2a1 1 0 1 0 2 0zm8-2a1 1 0 1 0-2 0zm-2 2a1 1 0 1 0 2 0zM6 7v1h12V6H6zm15 3h-1v7h2v-7zm-3 10v-1H6v2h12zM3 17h1v-7H2v7zM7 4l-.832.555l2 3L9 7l.832-.555l-2-3zm10 0l-.832-.555l-2 3L15 7l.832.555l2-3zm-8 8H8v2h2v-2zm6 0h-1v2h2v-2zm-9 8v-1a2 2 0 0 1-2-2H2a4 4 0 0 0 4 4zm15-3h-1a2 2 0 0 1-2 2v2a4 4 0 0 0 4-4zM18 7v1a2 2 0 0 1 2 2h2a4 4 0 0 0-4-4zM6 7V6a4 4 0 0 0-4 4h2a2 2 0 0 1 2-2z"
      />
    </Svg>
  );
}
