// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: bluesky-social-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function BlueskySocialLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="m3.655 9.38l-.313-3.288c-.149-1.564 1.486-2.68 2.805-1.828C8.97 6.086 10.484 7.969 12 11c1.516-3.031 3.031-4.914 5.853-6.736c1.32-.852 2.954.264 2.805 1.828l-.313 3.287A4 4 0 0 1 16.363 13H15l2.34.936c1.407.563 2.002 2.248 1.093 3.46A10.5 10.5 0 0 1 17.5 18.5c-.275.275-.61.557-.963.827c-1.25.958-3 .282-3.498-1.211L12 15l-1.039 3.116c-.498 1.494-2.248 2.17-3.498 1.211A10 10 0 0 1 6.5 18.5c-.311-.311-.631-.7-.934-1.104c-.908-1.212-.313-2.897 1.094-3.46L9 13H7.637a4 4 0 0 1-3.982-3.62"
      />
    </Svg>
  );
}
