// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: book-3-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Book3Fill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M3.057 2.666A1 1 0 0 1 4 2h12.5a4.5 4.5 0 1 1 0 9H4a1 1 0 0 1-.629-1.777a3.5 3.5 0 0 0 1.3-2.723c0-1.1-.505-2.08-1.3-2.723a1 1 0 0 1-.314-1.11M3 16.5A4.5 4.5 0 0 1 7.5 12H20a1 1 0 0 1 .629 1.777a3.5 3.5 0 0 0-1.3 2.723c0 1.1.505 2.08 1.3 2.723A1 1 0 0 1 20 21H7.5A4.5 4.5 0 0 1 3 16.5"
        clipRule="evenodd"
      />
    </Svg>
  );
}
