// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: bookmark-edit-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function BookmarkEditFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M18.677 15.033a2.5 2.5 0 0 1 3.535 3.536l-3.417 3.417a1.5 1.5 0 0 1-.849.425l-2.308.33a1 1 0 0 1-1.133-1.133l.33-2.308a1.5 1.5 0 0 1 .424-.849zM16 3a3 3 0 0 1 3 3v6.54a4.5 4.5 0 0 0-1.737 1.08l-3.418 3.417a3.5 3.5 0 0 0-.95 1.76L12 18.203l-4.668 3.111C6.335 21.979 5 21.264 5 20.066V6a3 3 0 0 1 3-3z"
      />
    </Svg>
  );
}
