// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: book-3-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Book3Line({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinejoin="round"
        strokeWidth="2"
        d="M4 10a4.5 4.5 0 0 0 1.671-3.5A4.5 4.5 0 0 0 4 3h12.5a3.5 3.5 0 1 1 0 7zm16 10a4.5 4.5 0 0 1-1.671-3.5c0-1.414.651-2.675 1.671-3.5H7.5a3.5 3.5 0 1 0 0 7z"
      />
    </Svg>
  );
}
