// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: border-radius-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function BorderRadiusFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="3"
        d="M4 4h.01M8 4h.01M4 8h.01M4 12h.01M4 16h.01M20 16h.01M4 20h.01M8 20h.01M12 20h.01M16 20h.01M20 20h.01M12 4h2a6 6 0 0 1 6 6v2"
      />
    </Svg>
  );
}
