// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: border-vertical-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function BorderVerticalLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M8 4h.01M4 4h.01M16 4h.01M20 4h.01M4 8h.01M20 8h.01M8 12h.01M4 12h.01M16 12h.01M20 12h.01M4 16h.01M20 16h.01M8 20h.01M4 20h.01M16 20h.01M20 20h.01M12 4v16"
      />
    </Svg>
  );
}
