// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: box-2-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Box2Line({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M10 14h4M4 8h16v11a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1zm17 0V5a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v3z"
      />
    </Svg>
  );
}
