// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: brain-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function BrainFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        d="M15 3a4 4 0 0 1 4 4v1.126a4.002 4.002 0 0 1 0 7.748V17a4 4 0 0 1-7 2.645A4 4 0 0 1 5 17v-1.126a4.002 4.002 0 0 1 0-7.748V7a4 4 0 0 1 7-2.646A4 4 0 0 1 15 3m-3 3a1 1 0 0 0-1 1v4.536A4 4 0 0 0 9 11a1 1 0 0 0 0 2a2 2 0 0 1 2 2v2a1 1 0 0 0 2 0v-2a2 2 0 0 1 2-2a1 1 0 0 0 0-2c-.729 0-1.412.196-2 .536V7a1 1 0 0 0-1-1"
      />
    </Svg>
  );
}
