// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: brief-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function BriefFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M3.084 5.467C3.588 4.479 4.61 4 5.584 4h12.833c.973 0 1.995.479 2.499 1.467A9.96 9.96 0 0 1 22 10c0 5.523-4.477 10-10 10S2 15.523 2 10c0-1.63.39-3.171 1.084-4.533m16.662 6.54A5 5 0 0 0 15 17v.419a8.02 8.02 0 0 0 4.746-5.413M9 17.418a8.02 8.02 0 0 1-4.746-5.413A5 5 0 0 1 9 17z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
