// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: building-5-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Building5Line({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M3 20h18M8 20V5a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v15m0-10h3a1 1 0 0 1 1 1v9M8 8H5a1 1 0 0 0-1 1v11m7.5-12h1m-1 4h1m-1 4h1"
      />
    </Svg>
  );
}
