// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: building-4-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Building4Fill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M10.753 2.197a2 2 0 0 0-1.662.182l-4.12 2.472A2 2 0 0 0 4 6.566V20H3a1 1 0 1 0 0 2h18a1 1 0 1 0 0-2h-1V6.72a2 2 0 0 0-1.367-1.896zM9 4.767l-3 1.8V20h3z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
