// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: burj-khalifa-tower-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function BurjKhalifaTowerFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M13 2a1 1 0 1 0-2 0v2a1 1 0 0 0-1 1v2.134A1 1 0 0 0 9.5 8v3.134A1 1 0 0 0 9 12v3a1 1 0 0 0-1 1v5a1 1 0 1 0 0 2h8a1 1 0 1 0 0-2v-4a1 1 0 0 0-1-1v-3a1 1 0 0 0-.5-.866V9a1 1 0 0 0-.5-.866V5a1 1 0 0 0-1-1z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
