// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: cactus-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function CactusFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M12 2a4 4 0 0 0-4 4v6H7a1 1 0 0 1-1-1V9a1 1 0 0 0-2 0v2a3 3 0 0 0 3 3h1v6H6a1 1 0 1 0 0 2h12a1 1 0 1 0 0-2h-2v-4h1a3 3 0 0 0 3-3V8a1 1 0 1 0-2 0v5a1 1 0 0 1-1 1h-1V6a4 4 0 0 0-4-4"
        clipRule="evenodd"
      />
    </Svg>
  );
}
