// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: camcorder-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function CamcorderFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M16 4a2 2 0 0 1 2 2v2.209l2.095-1.29A1.25 1.25 0 0 1 22 7.983v8.034a1.25 1.25 0 0 1-1.905 1.064L18 15.79V18a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2z"
      />
    </Svg>
  );
}
