// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: camera-2-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Camera2Line({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeWidth="2"
        d="M3 7a1 1 0 0 1 1-1h2.586a1 1 0 0 0 .707-.293l1.414-1.414A1 1 0 0 1 9.414 4h5.172a1 1 0 0 1 .707.293l1.414 1.414a1 1 0 0 0 .707.293H20a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z"
      />
      <SvgPath fill="none" stroke={color} strokeWidth="2" d="M16 12.5a4 4 0 1 1-8 0a4 4 0 0 1 8 0Z" />
    </Svg>
  );
}
