// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: campground-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function CampgroundFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M14.824 4.567a1 1 0 0 0-1.648-1.133L12 5.144l-1.176-1.71a1 1 0 1 0-1.648 1.133l1.61 2.342L2.475 19H2a1 1 0 1 0 0 2h4.633l.045-.07l4.492-6.487a1.01 1.01 0 0 1 1.66 0l4.492 6.488q.024.034.044.07H22a1 1 0 1 0 0-2h-.474L13.214 6.908z"
      />
      <SvgPath fill={color} d="M14.938 21L12 16.757L9.062 21z" />
    </Svg>
  );
}
