// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: cardboard-vr-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function CardboardVrFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M19 5a3 3 0 0 1 3 3v8a3 3 0 0 1-3 3h-2.172a3 3 0 0 1-2.121-.879l-1.828-1.828a1 1 0 0 0-.707-.293h-.344a1 1 0 0 0-.707.293l-1.828 1.828A3 3 0 0 1 7.172 19H5a3 3 0 0 1-3-3V8a3 3 0 0 1 3-3zM8 9a2 2 0 1 0 0 4a2 2 0 0 0 0-4m8 0a2 2 0 1 0 0 4a2 2 0 0 0 0-4"
      />
    </Svg>
  );
}
