// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: cash-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function CashLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeWidth="2"
        d="M5.625 6A1.875 1.875 0 0 1 3 8.625M5.625 18A1.875 1.875 0 0 0 3 15.375M18.375 6A1.875 1.875 0 0 0 21 8.625M18.375 18A1.875 1.875 0 0 1 21 15.375M15 12a3 3 0 1 1-6 0a3 3 0 0 1 6 0ZM4 18h16a1 1 0 0 0 1-1V7a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1Z"
      />
    </Svg>
  );
}
