// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: chart-pie-2-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function ChartPie2Line({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        d="M8.89 4.627a1 1 0 0 0-.78-1.842l.39.92zM21.214 15.89a1 1 0 1 0-1.842-.778l.921.39zM12 3V2a1 1 0 0 0-1 1zm9 9v1a1 1 0 0 0 1-1zm-9 0h-1a1 1 0 0 0 1 1zm0 9v-1a8 8 0 0 1-8-8H2c0 5.523 4.477 10 10 10zm-9-9h1a8 8 0 0 1 4.89-7.373l-.39-.921l-.39-.921A10 10 0 0 0 2 12zm17.294 3.5l-.921-.39A8 8 0 0 1 12 20v2c4.145 0 7.699-2.522 9.215-6.11zM21 12v-1h-9v2h9zm-9 0h1V3h-2v9zm0-9v1a8 8 0 0 1 8 8h2c0-5.523-4.477-10-10-10z"
      />
    </Svg>
  );
}
