// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: chat-4-ai-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Chat4AiLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M9 11v2m6-2v2m-2-9H7a4 4 0 0 0-4 4v12h14a4 4 0 0 0 4-4v-4M20 2l.13.378a4 4 0 0 0 2.492 2.493L23 5l-.378.13a4 4 0 0 0-2.493 2.492L20 8l-.13-.378a4 4 0 0 0-2.492-2.493L17 5l.378-.13a4 4 0 0 0 2.493-2.492z"
      />
    </Svg>
  );
}
