// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: check-2-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Check2Line({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinejoin="round"
        strokeWidth="2"
        d="M20.01 3.99L21 5.502s-7.047 6.577-10.667 12.9a.51.51 0 0 1-.808.106L3.04 11.77L5 10l4 3c5.5-5.5 8.5-7.5 11.01-9.01Z"
      />
    </Svg>
  );
}
