// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: chef-hat-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function ChefHatFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M12 3c1.728 0 3.25.877 4.148 2.207A4.5 4.5 0 0 1 19 13.744V18a3 3 0 0 1-3 3H8a3 3 0 0 1-3-3v-4.256a4.502 4.502 0 0 1 2.853-8.537A5 5 0 0 1 12 3M7 18a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-1H7z"
      />
    </Svg>
  );
}
