// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: church-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function ChurchFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M12 2a1 1 0 0 1 1 1v1h1a1 1 0 1 1 0 2h-1v1.5l3.6 2.7a1 1 0 0 1 .4.8v1.465l2.555 1.703A1 1 0 0 1 20 15v5a1 1 0 1 1 0 2H4a1 1 0 1 1 0-2v-5a1 1 0 0 1 .445-.832L7 12.465V11a1 1 0 0 1 .4-.8L11 7.5V6h-1a1 1 0 0 1 0-2h1V3a1 1 0 0 1 1-1m0 13a2 2 0 0 0-2 2v3h4v-3a2 2 0 0 0-2-2"
      />
    </Svg>
  );
}
