// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: classify-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function ClassifyFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M7 3a4 4 0 1 0 0 8a4 4 0 0 0 0-8m0 10a4 4 0 1 0 0 8a4 4 0 0 0 0-8m6-6a4 4 0 1 1 8 0a4 4 0 0 1-8 0m4 6a4 4 0 1 0 0 8a4 4 0 0 0 0-8"
        clipRule="evenodd"
      />
    </Svg>
  );
}
