// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: clockwise-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function ClockwiseFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        d="M20 8a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H10a2 2 0 0 1-2-2v-9a2 2 0 0 1 2-2zm-8.945-5c.788 0 1.057.688 1.097.972s-.026 1.002-.76 1.233c-.928.291-2.462.873-3.936 1.875c-1.474 1.001-2.834 2.384-3.517 4.262a1 1 0 1 1-1.879-.684c.872-2.397 2.578-4.082 4.272-5.232Q6.663 5.2 6.996 5H6a1 1 0 0 1 0-2z"
      />
    </Svg>
  );
}
