// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: close-medium-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function CloseMediumLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath fill="none" stroke={color} strokeLinecap="round" strokeWidth="2" d="m7.05 7.05l9.9 9.9m-9.9 0l9.9-9.9" />
    </Svg>
  );
}
