// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: coat-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function CoatLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="m7 18l-3.248-1.624a1 1 0 0 1-.51-1.182l2.261-7.539a4 4 0 0 1 2.043-2.428l2.032-1.016A2 2 0 0 1 10.472 4h3.056a2 2 0 0 1 .894.211l2.032 1.016a4 4 0 0 1 2.043 2.428l2.261 7.54a1 1 0 0 1-.51 1.181L17 18m-9.5-4l-.32 3.834A2 2 0 0 0 9.175 20h5.652a2 2 0 0 0 1.994-2.166L16.5 14M12 11v9m0-9L8.444 4.778M12 11l3.556-6.222"
      />
    </Svg>
  );
}
