// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: codepen-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function CodepenFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeWidth="3"
        d="m3.046 9.025l8.454 4.881a1 1 0 0 0 1 0l8.454-4.88m-17.93 5.961l8.476-4.893a1 1 0 0 1 1 0l8.476 4.893M12 4v6m0 4v6M3.002 9.577v4.845a1 1 0 0 0 .5.866l7.998 4.618a1 1 0 0 0 1 0l7.998-4.618a1 1 0 0 0 .5-.866V9.577a1 1 0 0 0-.5-.866L12.5 4.093a1 1 0 0 0-1 0L3.502 8.711a1 1 0 0 0-.5.866Z"
      />
    </Svg>
  );
}
