// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: coin-2-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Coin2Line({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeWidth="2"
        d="M20 7.5c0 1.933-3.582 3.5-8 3.5S4 9.433 4 7.5m16 0C20 5.567 16.418 4 12 4S4 5.567 4 7.5m16 0v10c0 1.933-3.582 3.5-8 3.5s-8-1.567-8-3.5v-10m16 5c0 1.933-3.582 3.5-8 3.5s-8-1.567-8-3.5"
      />
    </Svg>
  );
}
