// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: color-filter-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function ColorFilterLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeWidth="2"
        d="M12 13a5 5 0 1 1 4-2m-4 2a4.99 4.99 0 0 1 4-2m-4 2a5 5 0 1 1-4-2m8 0a5 5 0 1 1-4 8"
      />
    </Svg>
  );
}
