// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: components-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function ComponentsFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M10.94 2.454a1.5 1.5 0 0 1 2.12 0l2.83 2.829a1.5 1.5 0 0 1 0 2.121l-2.83 2.828a1.5 1.5 0 0 1-2.12 0L8.11 7.404a1.5 1.5 0 0 1 0-2.121zm5.656 5.657a1.5 1.5 0 0 1 2.122 0l2.828 2.829a1.5 1.5 0 0 1 0 2.12l-2.828 2.83a1.5 1.5 0 0 1-2.122 0l-2.828-2.83a1.5 1.5 0 0 1 0-2.12zm-11.314 0a1.5 1.5 0 0 1 2.122 0l2.828 2.829a1.5 1.5 0 0 1 0 2.12l-2.828 2.83a1.5 1.5 0 0 1-2.122 0l-2.828-2.83a1.5 1.5 0 0 1 0-2.12zm5.657 5.657a1.5 1.5 0 0 1 2.122 0l2.828 2.828a1.5 1.5 0 0 1 0 2.122l-2.828 2.828a1.5 1.5 0 0 1-2.122 0l-2.828-2.828a1.5 1.5 0 0 1 0-2.122z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
