// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: contacts-3-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Contacts3Fill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M16 3a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2zm3.975 1.938A1.5 1.5 0 0 1 21 6.36v11.28a1.5 1.5 0 0 1-1.025 1.422l-.975.325V4.612zM11 13c-.841 0-1.74.137-2.469.46C7.837 13.77 7 14.405 7 15.5a1 1 0 0 0 2 .016c.024-.033.125-.13.344-.227C9.74 15.113 10.34 15 11 15s1.26.113 1.656.29c.22.097.32.194.344.226a1 1 0 0 0 2-.016c0-1.096-.837-1.73-1.531-2.04C12.74 13.138 11.84 13 11 13m0-5a2 2 0 1 0 0 4a2 2 0 0 0 0-4"
      />
    </Svg>
  );
}
