// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: content-ai-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function ContentAiLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M4 19h1m9 0h1m-6 0h1m9 0h1M4 12h6M4 5h16m-3 4l.13.378a4 4 0 0 0 2.492 2.493L20 12l-.378.13a4 4 0 0 0-2.493 2.492L17 15l-.13-.378a4 4 0 0 0-2.492-2.493L14 12l.378-.13a4 4 0 0 0 2.493-2.492z"
      />
    </Svg>
  );
}
