// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: cookie-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function CookieLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        d="M10 9.5a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0m0 6a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0m6-2a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0"
      />
      <SvgPath
        fill="none"
        stroke={color}
        strokeWidth="2"
        d="M17 7a.125.125 0 0 0-.16-.12A3 3 0 0 1 13 4c0-.49-.304-.987-.794-.998L12 3a9 9 0 1 0 8.9 7.653c-.062-.414-.481-.653-.9-.653a3 3 0 0 1-3-3Z"
      />
      <SvgPath
        fill="none"
        stroke={color}
        strokeWidth="2"
        d="M10 9.5a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0Zm0 6a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0Zm6-2a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0Z"
      />
    </Svg>
  );
}
