// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: cookie-man-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function CookieManFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        d="M12 2a4 4 0 0 1 3.949 4.64l.206-.055a3 3 0 0 1 1.554 5.795l-1.71.458v.76l1.85 3.2a3 3 0 0 1-5.197 3L12 18.67l-.652 1.129a3 3 0 0 1-5.196-3L8 13.598v-.76l-1.708-.458a3 3 0 1 1 1.552-5.795l.206.055A4 4 0 0 1 12 2m0 11a1 1 0 1 0 0 2a1 1 0 0 0 0-2m0-3a1 1 0 1 0 0 2a1 1 0 0 0 0-2"
      />
    </Svg>
  );
}
