// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: crutch-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function CrutchLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeWidth="2"
        d="M7 8v1.5a1.5 1.5 0 0 0 3 0V8a2 2 0 1 1 4 0v11.5a1.5 1.5 0 0 0 3 0V8A5 5 0 0 0 7 8Z"
      />
    </Svg>
  );
}
