// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: cupcake-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function CupcakeLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="m19 13.5l-2.464 5.338A2 2 0 0 1 14.72 20H9.28a2 2 0 0 1-1.816-1.162L5 13.5m2 .5a3 3 0 1 1 .1-5.998a5.002 5.002 0 0 1 9.8 0L17 8a3 3 0 1 1 0 6z"
      />
    </Svg>
  );
}
