// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: currency-rupee-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function CurrencyRupeeFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12S6.477 2 12 2M9 7a1 1 0 0 0 0 2h1a2 2 0 0 1 1.732 1H9a1 1 0 1 0 0 2h2.732A2 2 0 0 1 10 13h-.999a1 1 0 0 0-.73.315c-.169.18-.27.427-.271.684a.99.99 0 0 0 .408.808L12.4 17.8a1 1 0 1 0 1.2-1.6l-2.028-1.521A4.01 4.01 0 0 0 13.874 12H15a1 1 0 1 0 0-2h-1.126a4 4 0 0 0-.41-1H15a1 1 0 1 0 0-2z"
      />
    </Svg>
  );
}
