// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: currency-bitcoin-2-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function CurrencyBitcoin2Fill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="3"
        d="M6 6h8a3 3 0 1 1 0 6H8m-2 6h8.005a2.995 2.995 0 1 0 0-5.99H8M9 6V4m0 16v-2m4-12V4m0 16v-2m-5 0V6"
      />
    </Svg>
  );
}
