// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: currency-euro-2-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function CurrencyEuro2Line({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M5 10h8m-8 4h8m5-7c-1.167-1.237-2.766-2-4.529-2C9.897 5 7 8.134 7 12s2.897 7 6.471 7c1.763 0 3.362-.763 4.529-2"
      />
    </Svg>
  );
}
