// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: currency-cny-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function CurrencyCnyFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10s10-4.477 10-10S17.523 2 12 2M8.4 7.2a1 1 0 0 1 1.4.2l2.2 2.933L14.2 7.4a1 1 0 1 1 1.6 1.2L14 11h1a1 1 0 0 1 0 2h-2v1h2a1 1 0 0 1 0 2h-2v1a1 1 0 0 1-2 0v-1H9a1 1 0 0 1 0-2h2v-1H9a1 1 0 0 1 0-2h1L8.2 8.6a1 1 0 0 1 .2-1.4"
        clipRule="evenodd"
      />
    </Svg>
  );
}
