// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: danmaku-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function DanmakuFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M18 3a3 3 0 0 1 3 3v9a3 3 0 0 1-3 3h-6.667L8 20.5c-.824.618-2 .03-2-1V18H5a3 3 0 0 1-3-3V6a3 3 0 0 1 3-3zM3 12a1 1 0 1 0 0 2h6a1 1 0 1 0 0-2zm10 0a1 1 0 1 0 0 2h2a1 1 0 1 0 0-2zM5 7a1 1 0 0 0 0 2h2a1 1 0 0 0 0-2zm6 0a1 1 0 1 0 0 2h8a1 1 0 1 0 0-2z"
      />
    </Svg>
  );
}
