// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: dashboard-4-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Dashboard4Fill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12S6.477 2 12 2M6.438 9.531a1 1 0 0 0-1.217.72a7.01 7.01 0 0 0 1.561 6.416a1 1 0 0 0 1.49-1.334A4.98 4.98 0 0 1 7 12q.002-.651.157-1.251a1 1 0 0 0-.719-1.218M12 5a7 7 0 0 0-1.749.22a1 1 0 0 0 .498 1.937a5 5 0 0 1 4.978 8.176a1 1 0 0 0 1.49 1.334A7 7 0 0 0 12 5M7.707 6.293a1 1 0 1 0-1.414 1.414l3.776 3.776a2 2 0 1 0 1.414-1.414z"
      />
    </Svg>
  );
}
