// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: desk-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function DeskFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M2 6a1 1 0 0 1 1-1h18a1 1 0 1 1 0 2v12a1 1 0 1 1-2 0v-2h-4a1 1 0 0 1-1-1v-5H5v8a1 1 0 1 1-2 0V7a1 1 0 0 1-1-1m14 1v2h3V7zm3 5h-3v2h3z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
