// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: diamond-square-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function DiamondSquareLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinejoin="round"
        strokeWidth="2"
        d="M11.293 3.516a1 1 0 0 1 1.414 0l7.778 7.778a1 1 0 0 1 0 1.414l-7.778 7.778a1 1 0 0 1-1.414 0l-7.778-7.778a1 1 0 0 1 0-1.414z"
      />
    </Svg>
  );
}
