// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: direction-arrow-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function DirectionArrowLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="m11 17l1 1l1-1m-6-6l-1 1l1 1m4-6l1-1l1 1m4 4l1 1l-1 1m4-1a9 9 0 1 1-18 0a9 9 0 0 1 18 0"
      />
    </Svg>
  );
}
