// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: dish-cover-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function DishCoverLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M4 20h16M10 4h4m-2 0v3m7 10H5C3.084 12.21 6.612 7 11.77 7h.46c5.158 0 8.686 5.21 6.77 10Z"
      />
    </Svg>
  );
}
