// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: doc-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function DocFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M12 8.5a1.5 1.5 0 0 0 1.5 1.5H20v10a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h6zm3.352 4.563a1 1 0 0 0-1.289.585L13.5 15.15l-.563-1.502a1 1 0 0 0-1.808-.14l-.066.14l-.563 1.502l-.563-1.502a1 1 0 0 0-1.874.704l1.5 4a1 1 0 0 0 1.874 0L12 16.849l.563 1.503a1 1 0 0 0 1.874 0l1.5-4a1 1 0 0 0-.585-1.289M14 2.043a2 2 0 0 1 1 .543L19.414 7a2 2 0 0 1 .541 1H14z"
      />
    </Svg>
  );
}
