// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: dot-grid-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function DotGridFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M7.5 5.5a2 2 0 1 1-4 0a2 2 0 0 1 4 0m0 6.5a2 2 0 1 1-4 0a2 2 0 0 1 4 0m0 6.5a2 2 0 1 1-4 0a2 2 0 0 1 4 0m6.5-13a2 2 0 1 1-4 0a2 2 0 0 1 4 0m0 6.5a2 2 0 1 1-4 0a2 2 0 0 1 4 0m0 6.5a2 2 0 1 1-4 0a2 2 0 0 1 4 0m6.5-13a2 2 0 1 1-4 0a2 2 0 0 1 4 0m0 6.5a2 2 0 1 1-4 0a2 2 0 0 1 4 0m0 6.5a2 2 0 1 1-4 0a2 2 0 0 1 4 0"
      />
    </Svg>
  );
}
