// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: download-3-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Download3Line({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M12 12v9m-3-3l3 2.995L15 18m-9.5-1.29a4.001 4.001 0 0 1 .526-7.59a.01.01 0 0 0 .007-.011a5.5 5.5 0 0 1 10.776-2.05a.01.01 0 0 0 .008.007a5.001 5.001 0 0 1 1.683 9.265"
      />
    </Svg>
  );
}
