// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: drink-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function DrinkLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M7 8V5.5a.5.5 0 0 1 .5-.5H12m5 3V5.5a.5.5 0 0 0-.5-.5H12m-6 5V8.5a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 .5.5V10m-5-7l-1 1.409v.59m-5 6h10l-.91 9.1a1 1 0 0 1-.995.9h-6.19a1 1 0 0 1-.995-.9z"
      />
    </Svg>
  );
}
