// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: drum-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function DrumLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M3.5 9h17M3.512 15H20.5m.5-3a8.98 8.98 0 0 0-3.072-6.772a.95.95 0 0 0-.625-.228H6.697a.94.94 0 0 0-.625.228A8.98 8.98 0 0 0 3 12a8.98 8.98 0 0 0 3.072 6.772a.95.95 0 0 0 .625.228h10.606a.95.95 0 0 0 .625-.228A8.98 8.98 0 0 0 21 12"
      />
    </Svg>
  );
}
