// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: dry-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function DryFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M17.557 2.608a1.5 1.5 0 0 1 .836 1.95l-.828 2.069a4.5 4.5 0 0 0 .434 4.167l.498.748a7.5 7.5 0 0 1 .724 6.946l-.828 2.07a1.5 1.5 0 1 1-2.786-1.115l.828-2.07a4.5 4.5 0 0 0-.434-4.167l-.498-.747a7.5 7.5 0 0 1-.724-6.946l.828-2.07a1.5 1.5 0 0 1 1.95-.835"
        clipRule="evenodd"
      />
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M12.557 2.608a1.5 1.5 0 0 1 .836 1.95l-.828 2.069a4.5 4.5 0 0 0 .434 4.167l.498.748a7.5 7.5 0 0 1 .723 6.946l-.827 2.07a1.5 1.5 0 1 1-2.786-1.115l.828-2.07a4.5 4.5 0 0 0-.434-4.167l-.498-.747a7.5 7.5 0 0 1-.724-6.946l.828-2.07a1.5 1.5 0 0 1 1.95-.835"
        clipRule="evenodd"
      />
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M7.557 2.608a1.5 1.5 0 0 1 .836 1.95l-.828 2.069a4.5 4.5 0 0 0 .434 4.167l.498.748a7.5 7.5 0 0 1 .723 6.946l-.827 2.07a1.5 1.5 0 1 1-2.786-1.115l.828-2.07a4.5 4.5 0 0 0-.434-4.167l-.498-.747a7.5 7.5 0 0 1-.724-6.946l.828-2.07a1.5 1.5 0 0 1 1.95-.835"
        clipRule="evenodd"
      />
    </Svg>
  );
}
