// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: earth-latitude-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function EarthLatitudeFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        d="M19.14 19A9.97 9.97 0 0 1 12 22a9.97 9.97 0 0 1-7.14-3zm2.81-6a9.9 9.9 0 0 1-1.291 4H3.34a9.9 9.9 0 0 1-1.292-4zm-1.29-6a9.9 9.9 0 0 1 1.292 4H2.049a9.9 9.9 0 0 1 1.292-4zM12 2a9.97 9.97 0 0 1 7.14 3H4.861A9.97 9.97 0 0 1 12 2"
      />
    </Svg>
  );
}
