// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: ease-in-out-control-point-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function EaseInOutControlPointLine({
  size = 24,
  color: colorProp,
  style,
  accessibilityLabel,
  testID,
  ...props
}: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M20 4c-8 0-8 16-16 16M8 4a2 2 0 1 1-4 0a2 2 0 0 1 4 0Zm0 0h2m3 0h1m2 16a2 2 0 1 0 4 0a2 2 0 0 0-4 0Zm0 0h-2m-4 0h1"
      />
    </Svg>
  );
}
