// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: ease-in-control-point-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function EaseInControlPointLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M20 4c-.5 1-8 16-16 16m13 0a2 2 0 1 0 4 0a2 2 0 0 0-4 0Zm0 0h-2m-4 0h1"
      />
    </Svg>
  );
}
