// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: edit-3-ai-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Edit3AiLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M9 21h11M3.996 21H9.24a1 1 0 0 0 .707-.292L20.26 10.394a1 1 0 0 0 0-1.414l-4.243-4.243a1 1 0 0 0-1.414 0L4.289 15.051a1 1 0 0 0-.293.707zM5 2l.13.378a4 4 0 0 0 2.492 2.493L8 5l-.378.13a4 4 0 0 0-2.493 2.492L5 8l-.13-.378a4 4 0 0 0-2.492-2.493L2 5l.378-.13a4 4 0 0 0 2.493-2.492z"
      />
    </Svg>
  );
}
