// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: edit-2-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Edit2Line({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="m12.17 6.17l-7.88 7.881a1 1 0 0 0-.294.707v5.243H9.24a1 1 0 0 0 .707-.293l7.88-7.88M12.17 6.17l2.433-2.433a1 1 0 0 1 1.414 0L20.26 7.98a1 1 0 0 1 0 1.414l-2.433 2.433M12.17 6.17l5.657 5.657"
      />
    </Svg>
  );
}
