// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: egg-crack-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function EggCrackLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="m13 13l1-3l-3-1l3.78-4.725M19 13.5c0 4.5-3 7.5-7 7.5s-7-3-7-7.5C5 8.5 9 3 12 3s7 5.5 7 10.5"
      />
    </Svg>
  );
}
