// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: egyptian-pyramids-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function EgyptianPyramidsFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M15 6a1 1 0 0 1 .844.463l7 11A1 1 0 0 1 22 19H2a1 1 0 0 1-.79-1.614l7-9a1 1 0 0 1 1.58 0l1.73 2.23l2.636-4.152A1 1 0 0 1 14.999 6m-1.272 7.45l.274-3.012l-1.177 1.852zM6.246 17l1.278-4.473L4.044 17z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
