// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: egyptian-pyramids-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function EgyptianPyramidsLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M11 11.571L16 18m-9 0l2.418-8.462M14.5 16l.778-8.562m0 0L15 7l-3.398 5.352l-2.184-2.814L9 9l-7 9h20z"
      />
    </Svg>
  );
}
