// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: eiffel-tower-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function EiffelTowerLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M12 2v3m-1 1h2m-4 8h6m-8 3h10M5 22h4s.906-2 3-2s3 2 3 2h4s-3.5-4-5-8s-2-10-2-10s-.5 6-2 10s-5 8-5 8"
      />
    </Svg>
  );
}
