// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: electric-cooker-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function ElectricCookerFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        d="M21 10a1 1 0 1 1 0 2h-1v7a3 3 0 0 1-3 3H7a3 3 0 0 1-3-3v-7H3a1 1 0 1 1 0-2zm-9 3a3 3 0 1 0 0 6a3 3 0 0 0 0-6m0 2a1 1 0 1 1 0 2a1 1 0 0 1 0-2m0-13a3 3 0 0 1 3 3h1a4 4 0 0 1 4 4H4a4 4 0 0 1 4-4h1a3 3 0 0 1 3-3m0 2a1 1 0 0 0-1 1h2a1 1 0 0 0-1-1"
      />
    </Svg>
  );
}
