// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: emoji-2-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Emoji2Line({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="m15 8l-1 1l1 1M9 8v2m12 2a9 9 0 1 1-18 0a9 9 0 0 1 18 0m-9 6a4 4 0 0 1-4-4v-.167c0-.46.373-.833.833-.833h6.334c.46 0 .833.373.833.833V14a4 4 0 0 1-4 4"
      />
    </Svg>
  );
}
