// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: escalator-up-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function EscalatorUpFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M15.96 4a3 3 0 0 0-2.342 1.126L6.52 14H5a3 3 0 0 0 0 6h3.04a3 3 0 0 0 2.342-1.126L17.48 10H19a3 3 0 1 0 0-6zM6 3.172q-.084 0-.165.015l-.026.003l-.01.002l-.025.006l-.06.015l-.01.004l-.02.007l-.069.025l-.025.012a1 1 0 0 0-.297.204l-2.121 2.12A1 1 0 1 0 4.586 7L5 6.586v3.243a1 1 0 0 0 2 0V6.586L7.414 7a1 1 0 1 0 1.414-1.414L6.707 3.465a1 1 0 0 0-.296-.204l-.025-.012l-.07-.025l-.021-.008l-.068-.018l-.03-.007h-.006l-.088-.014A1 1 0 0 0 6 3.172"
      />
    </Svg>
  );
}
