// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: exchange-euro-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function ExchangeEuroFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M16 8.429C15.257 7.545 14.5 7 13.118 7C10.844 7 9 9.239 9 12s1.844 5 4.118 5c1.382 0 2.14-.545 2.882-1.429M8 10.5h4m-4 3h4"
      />
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="3"
        d="M3.811 8.264A9 9 0 0 1 14.33 3.307a9 9 0 0 1 6.672 8.622c0 .08-.088.126-.154.082l-2.678-1.804c-.091-.062-.03-.205.078-.181L20 10.41m.189 5.327A9.003 9.003 0 0 1 2.998 12.07c0-.08.088-.126.154-.081l2.678 1.804c.091.062.03.204-.078.18L4 13.59"
      />
    </Svg>
  );
}
