// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: exit-door-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function ExitDoorFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M15.542 3a3 3 0 0 0-.53.998h-.632a3 3 0 0 0 0 6h.63A2.99 2.99 0 0 0 18 12.115V19h1a1 1 0 1 1 0 2H3a1 1 0 1 1 0-2h1V5a2 2 0 0 1 2-2zM13.5 13a1.5 1.5 0 1 0 0 3a1.5 1.5 0 0 0 0-3m3.673-8.828a1 1 0 0 1 1.414 0l2.12 2.119a1 1 0 0 1 .001 1.414l-2.12 2.123a1 1 0 0 1-1.415-1.413l.416-.417h-3.21a1 1 0 0 1 0-2h3.207l-.413-.412a1 1 0 0 1 0-1.414"
      />
    </Svg>
  );
}
