// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: facebook-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function FacebookLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M12 21a9 9 0 1 0 0-18a9 9 0 0 0 0 18Zm0 0v-8m2.5-5H14a2 2 0 0 0-2 2v3m0 0h-2m2 0h2"
      />
    </Svg>
  );
}
