// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: faceid-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function FaceidFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        d="M4 14.5A1.5 1.5 0 0 1 5.5 16v2.5H8a1.5 1.5 0 0 1 0 3H5A2.5 2.5 0 0 1 2.5 19v-3A1.5 1.5 0 0 1 4 14.5m16 0a1.5 1.5 0 0 1 1.5 1.5v3a2.5 2.5 0 0 1-2.5 2.5h-3a1.5 1.5 0 0 1 0-3h2.5V16a1.5 1.5 0 0 1 1.5-1.5m-5.55-1a1.5 1.5 0 0 1 2.1 2.143A6.5 6.5 0 0 1 12 17.5c-1.77 0-3.379-.71-4.55-1.858a1.5 1.5 0 0 1 2.1-2.143A3.5 3.5 0 0 0 12 14.501c.954 0 1.817-.38 2.45-1.001M9 8a2 2 0 1 1 0 4a2 2 0 0 1 0-4m6 0a2 2 0 1 1 0 4a2 2 0 0 1 0-4M8 2.5a1.5 1.5 0 1 1 0 3H5.5V8a1.5 1.5 0 1 1-3 0V5A2.5 2.5 0 0 1 5 2.5zm11 0A2.5 2.5 0 0 1 21.5 5v3a1.5 1.5 0 0 1-3 0V5.5H16a1.5 1.5 0 0 1 0-3z"
      />
    </Svg>
  );
}
