// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: face-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function FaceFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M6.356 4.164C7.726 2.784 9.622 2 12 2s4.273.785 5.644 2.164c1.156 1.163 1.88 2.69 2.25 4.373q.083.015.164.038c.869.232 1.429.916 1.702 1.65c.273.736.299 1.605.073 2.449c-.317 1.183-1.165 2.35-2.402 2.665C18.079 18.59 15.086 21 12 21s-6.08-2.412-7.431-5.662c-1.235-.317-2.081-1.483-2.398-2.664c-.226-.844-.2-1.713.073-2.45c.273-.733.833-1.417 1.702-1.65q.08-.021.16-.036c.37-1.684 1.094-3.21 2.25-4.374"
        clipRule="evenodd"
      />
    </Svg>
  );
}
