// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: factory-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function FactoryLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M3 20h18m-6 0c-1.705-6.82-1.957-13.641-1.994-15.504A.506.506 0 0 0 12.5 4H7.532a.51.51 0 0 0-.51.53C7.082 6.44 7.12 13.22 5 20m8.25-11h3.184c.3 0 .54.264.53.565c-.04 1.331.084 4.968 2.036 10.435"
      />
    </Svg>
  );
}
