// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: factory-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function FactoryFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M6.023 4.561A1.51 1.51 0 0 1 7.533 3H12.5c.82 0 1.49.654 1.506 1.476c.035 1.768.268 8.07 1.78 14.524h1c-.961-4.104-1.405-8.146-1.61-11h1.258c.906 0 1.555.773 1.53 1.595c-.034 1.161.06 4.434 1.747 9.405H21a1 1 0 1 1 0 2H3a1 1 0 1 1 0-2h1.257C6.112 12.616 6.08 6.365 6.023 4.561"
      />
    </Svg>
  );
}
