// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: fan-2-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Fan2Line({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeWidth="2"
        d="m12.013 12l-.013.013a4.68 4.68 0 0 0 3.31 1.367A4.68 4.68 0 0 0 18.633 12A4.69 4.69 0 0 0 12 5.367M12.013 12a4.68 4.68 0 0 0 1.367-3.31A4.68 4.68 0 0 0 12 5.367A4.69 4.69 0 0 0 5.367 12M12 11.987a4.68 4.68 0 0 0-1.38 3.323A4.68 4.68 0 0 0 12 18.633A4.69 4.69 0 0 0 18.633 12M12 11.987a4.68 4.68 0 0 0-3.31-1.367A4.68 4.68 0 0 0 5.367 12A4.69 4.69 0 0 0 12 18.633M12.013 12L12 11.987"
      />
    </Svg>
  );
}
