// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: fan-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function FanFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        d="M9 3.001c1.024-.768 4-1.5 6.5 1c.953.953.635 1.899-1.5 3.5c-.962.721-2.3 1.9-1.5 3.5c1.5-2.167 5.5-6 8.5-2c.768 1.025 1.5 4-1 6.5c-.953.953-1.899.635-3.5-1.5c-.721-.961-1.9-2.3-3.5-1.5c2.166 1.5 6 5.5 2 8.5c-1.025.768-4 1.5-6.5-1c-.953-.953-.635-1.899 1.5-3.5c.961-.721 2.3-1.9 1.5-3.5c-1.5 2.167-5.5 6-8.5 2c-.768-1.025-1.5-4 1-6.5c.953-.953 1.899-.635 3.5 1.5c.721.962 1.9 2.3 3.5 1.5c-2.167-1.5-6-5.5-2-8.5"
      />
    </Svg>
  );
}
