// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: fast-rewind-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function FastRewindFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M12.606 17.242c.063-.57.164-1.629.22-3.052a46 46 0 0 0 2.583 1.736c2.022 1.266 3.588 2.038 4.315 2.375a1.327 1.327 0 0 0 1.882-1.059c.093-.833.264-2.712.264-5.246c0-2.532-.171-4.41-.264-5.244a1.328 1.328 0 0 0-1.884-1.06a41 41 0 0 0-4.314 2.373a46 46 0 0 0-2.581 1.738a44 44 0 0 0-.221-3.051a1.328 1.328 0 0 0-1.884-1.06a41 41 0 0 0-4.314 2.373a42 42 0 0 0-4.1 2.899a1.33 1.33 0 0 0-.001 2.064c.607.495 2.026 1.6 4.102 2.898c2.022 1.266 3.588 2.038 4.315 2.375a1.327 1.327 0 0 0 1.882-1.059"
      />
    </Svg>
  );
}
