// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: file-security-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function FileSecurityFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M6 2a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h7.163A5.33 5.33 0 0 1 12 18.671V17a2 2 0 0 1 1.367-1.897l3-1a2 2 0 0 1 1.265 0l2.368.789V10h-6.5A1.5 1.5 0 0 1 12 8.5V2z"
      />
      <SvgPath
        fill={color}
        d="M14 2.043V8h5.957a2 2 0 0 0-.543-1L15 2.586a2 2 0 0 0-1-.543M17 16l-3 1v1.671a3.346 3.346 0 0 0 2.977 3.326a.2.2 0 0 0 .046 0A3.346 3.346 0 0 0 20 18.671V17z"
      />
    </Svg>
  );
}
