// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: file-code-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function FileCodeFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M12 8.5a1.5 1.5 0 0 0 1.5 1.5H20v10a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h6zm-.793 4.673a1 1 0 0 0-1.414 0l-2.121 2.12a1 1 0 0 0 0 1.415l2.121 2.122a1 1 0 0 0 1.414-1.415l-1.414-1.414l1.414-1.414a1 1 0 0 0 0-1.414m3 0a1 1 0 0 0-1.414 1.414L14.207 16l-1.414 1.414a1 1 0 0 0 1.414 1.415l2.122-2.122a1 1 0 0 0 0-1.414zM14 2.044a2 2 0 0 1 1 .542L19.414 7a2 2 0 0 1 .541 1H14z"
      />
    </Svg>
  );
}
