// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: file-music-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function FileMusicFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        d="M12 8.5a1.5 1.5 0 0 0 1.5 1.5H20v10a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h6zm2.448 4.184a1 1 0 0 0-1.264-.632l-1.159.386A1.5 1.5 0 0 0 11 13.86V15a2 2 0 1 0 2 2v-2.78l.816-.272a1 1 0 0 0 .632-1.264M14 2.044a2 2 0 0 1 1 .542L19.414 7a2 2 0 0 1 .541 1H14z"
      />
    </Svg>
  );
}
