// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: file-security-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function FileSecurityLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinejoin="round"
        strokeWidth="2"
        d="M19 9v-.586a1 1 0 0 0-.293-.707l-4.414-4.414A1 1 0 0 0 13.586 3H13m6 6v4m0-4h-5.5a.5.5 0 0 1-.5-.5V3m0 0H6a1 1 0 0 0-1 1v16a1 1 0 0 0 1 1h6m2-5l3-1l3 1v1.694a3.32 3.32 0 0 1-2.954 3.3a.4.4 0 0 1-.092 0a3.32 3.32 0 0 1-2.954-3.3z"
      />
    </Svg>
  );
}
