// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: filter-2-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Filter2Fill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M2.5 6A1.5 1.5 0 0 1 4 4.5h16a1.5 1.5 0 0 1 0 3H4A1.5 1.5 0 0 1 2.5 6m3 6A1.5 1.5 0 0 1 7 10.5h10a1.5 1.5 0 0 1 0 3H7A1.5 1.5 0 0 1 5.5 12m3 6a1.5 1.5 0 0 1 1.5-1.5h4a1.5 1.5 0 0 1 0 3h-4A1.5 1.5 0 0 1 8.5 18"
        clipRule="evenodd"
      />
    </Svg>
  );
}
