// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: fitness-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function FitnessLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinejoin="round"
        strokeWidth="2"
        d="M10 7.5c.5 1 1.5 1.5 2 1.5s3-2 2-4c-.5-1-3.815-.479-5 .5C4.16 9.5 3.62 16 4 17c.19.5 2.5 2.5 7 3c2.485.276 6.343.326 8-1c2.5-2 1.5-5 0-6c-2.25-1.5-5-.206-6 1c-1-1-2.5-1-4 0c-.5-2.5.5-5.5 1-6.5Z"
      />
    </Svg>
  );
}
