// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: flag-1-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Flag1Fill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M4 5a2 2 0 0 1 2-2h14a1 1 0 0 1 .809 1.588L17.236 9.5l3.573 4.912A1 1 0 0 1 20 16H6v5a1 1 0 1 1-2 0z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
