// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: flame-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function FlameFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M11.419 2.186a1 1 0 0 1 1.162 0a25 25 0 0 1 3.672 3.405C18.585 8.256 20 11.087 20 14a8 8 0 1 1-16 0c0-2.913 1.415-5.744 3.747-8.409a24.3 24.3 0 0 1 3.672-3.405m.586 9.314S8.31 14.139 8.31 17.305a3.694 3.694 0 1 0 7.388 0c0-3.155-3.667-5.786-3.694-5.805"
      />
    </Svg>
  );
}
