// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: flash-circle-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function FlashCircleLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath fill={color} d="M12.5 11.5L13 7l-4.5 6l3-.5L11 17l4.5-6z" />
      <SvgPath fill="none" stroke={color} strokeLinejoin="round" strokeWidth="2" d="M21 12a9 9 0 1 1-18 0a9 9 0 0 1 18 0Z" />
      <SvgPath fill="none" stroke={color} strokeLinejoin="round" strokeWidth="2" d="M12.5 11.5L13 7l-4.5 6l3-.5L11 17l4.5-6z" />
    </Svg>
  );
}
