// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: flight-inflight-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function FlightInflightLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M3 21h18M1.995 10h2.5l1 1.499l4.5-.5l-3-7h3l5 7l4.342.362a2.96 2.96 0 0 1 2.402 1.626l.042.084a.83.83 0 0 1-.051.826A2.47 2.47 0 0 1 19.67 15H3.996z"
      />
    </Svg>
  );
}
