// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: folder-minus-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function FolderMinusLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M9 13h6M9.52 4H4a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1V7.5a1 1 0 0 0-1-1h-7.52a1 1 0 0 1-.78-.375l-1.4-1.75A1 1 0 0 0 9.52 4"
      />
    </Svg>
  );
}
