// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: folder-security-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function FolderSecurityLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinejoin="round"
        strokeWidth="2"
        d="M21 13V7.5a1 1 0 0 0-1-1h-7.52a1 1 0 0 1-.78-.375l-1.4-1.75A1 1 0 0 0 9.52 4H4a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h8m3-4l3-1l3 1v1.671a3.346 3.346 0 0 1-2.977 3.326a.2.2 0 0 1-.046 0A3.346 3.346 0 0 1 15 17.671z"
      />
    </Svg>
  );
}
