// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: fold-vertical-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function FoldVerticalFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="3"
        d="M4 12h1m4 0h1m4 0h1m4 0h1m-8-9v5.5M9.172 6L12 8.828L14.83 6M12 15.5V21m-2.828-3L12 15.172L14.83 18"
      />
    </Svg>
  );
}
