// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: folder-open-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function FolderOpenFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M21.328 10a.5.5 0 0 1 .479.644l-2.89 9.643a1 1 0 0 1-.958.713H4c-.405 0-.782-.122-1.097-.33a.5.5 0 0 1-.01-.314l2.893-9.643A1 1 0 0 1 6.744 10zM9.52 3a2 2 0 0 1 1.561.751l1.4 1.749H19a2 2 0 0 1 2 2V8H6.744a3 3 0 0 0-2.874 2.138L2 16.37V5a2 2 0 0 1 2-2z"
      />
    </Svg>
  );
}
