// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: frame-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function FrameFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath fill="none" stroke={color} strokeLinecap="round" strokeWidth="3" d="M20 7H4m13 13V4m3 13H4m3 3V4" />
    </Svg>
  );
}
