// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: front-windshield-defroster-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function FrontWindshieldDefrosterLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M6 15L3.255 7.679c-.152-.405-.02-.856.361-1.059C4.706 6.04 7.313 5 12 5s7.294 1.04 8.384 1.62c.382.203.513.654.361 1.059L18 15m-8-4l-.233.291A3.16 3.16 0 0 0 10 15.5a3.16 3.16 0 0 1 .233 4.209L10 20m4-9l-.233.291A3.16 3.16 0 0 0 14 15.5a3.16 3.16 0 0 1 .233 4.209L14 20"
      />
    </Svg>
  );
}
