// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: git-branch-2-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function GitBranch2Fill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M17.5 3a3.5 3.5 0 0 1 .202 6.993a13.04 13.04 0 0 1-7.709 7.71A3.5 3.5 0 1 1 5.5 14.145V4a1 1 0 0 1 2 0v10.146a3.5 3.5 0 0 1 2.023 1.592a11.03 11.03 0 0 0 6.215-6.215A3.5 3.5 0 0 1 17.5 3"
      />
    </Svg>
  );
}
