// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: git-lab-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function GitLabLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinejoin="round"
        strokeWidth="2"
        d="m4.317 14.854l7.058 5.646a1 1 0 0 0 1.25 0l7.058-5.646a4 4 0 0 0 1.215-4.61L18 3l-2 6H8L6 3l-2.898 7.245a4 4 0 0 0 1.215 4.609Z"
      />
    </Svg>
  );
}
