// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: git-pull-request-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function GitPullRequestFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M6 3a2.998 2.998 0 0 1 1 5.825v6.349A2.999 2.999 0 0 1 6 21a3 3 0 0 1-1-5.826V8.825A2.998 2.998 0 0 1 6 3m6.793.172a1 1 0 1 1 1.414 1.414L13.793 5H16a3 3 0 0 1 3 3v7.174A2.999 2.999 0 0 1 18 21a3 3 0 0 1-1-5.826V8a1 1 0 0 0-1-1h-2.207l.414.414a1 1 0 0 1-1.414 1.414l-2.121-2.121a1 1 0 0 1 0-1.414z"
      />
    </Svg>
  );
}
