// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: git-lab-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function GitLabFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M6.03 2a1 1 0 0 1 .919.684L8.72 8h6.558l1.772-5.316a1 1 0 0 1 1.878-.055l2.897 7.244a5 5 0 0 1-1.518 5.762l-7.059 5.646a2 2 0 0 1-2.498 0l-7.058-5.646a5 5 0 0 1-1.52-5.762L5.073 2.63A1 1 0 0 1 6.029 2"
        clipRule="evenodd"
      />
    </Svg>
  );
}
