// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: glass-cup-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function GlassCupLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M6 9s2.5-1 6 .5s6 .5 6 .5m-8 3h.002M13 16h.002m3.103 5h-8.21a1 1 0 0 1-.994-.89L5.061 3.555A.5.5 0 0 1 5.56 3h12.88a.5.5 0 0 1 .497.555l-1.84 16.555a1 1 0 0 1-.993.89"
      />
    </Svg>
  );
}
