// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: google-gemini-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function GoogleGeminiLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinejoin="round"
        strokeWidth="2"
        d="M12 3s1.35 3.987 3.182 5.818S21 12 21 12s-3.987 1.35-5.818 3.182S12 21 12 21s-1.35-3.987-3.182-5.818S3 12 3 12s3.987-1.35 5.818-3.182S12 3 12 3Z"
      />
    </Svg>
  );
}
