// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: google-play-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function GooglePlayFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M15.677 17.092L8 21.525c-1.255.725-2.706.426-3.613-.466l7.623-7.644zm-5.078-5.093L3.506 19.11a3 3 0 0 1-.006-.182V5.07q0-.093.006-.185zM20 9.401c2 1.155 2 4.04 0 5.196l-2.531 1.46L13.422 12l4.048-4.06zM4.388 2.938c.907-.892 2.358-1.19 3.612-.465l7.679 4.433l-3.668 3.677z"
      />
    </Svg>
  );
}
