// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: hand-grab-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function HandGrabLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M11 7.5a1.5 1.5 0 0 0-3 0V11C6 8.5 5 8 3 9l3.065 6.13A7 7 0 0 0 12.326 19H13a7 7 0 0 0 7-7V9.5a1.5 1.5 0 0 0-3 0m-6-2v-1a1.5 1.5 0 0 1 3 0v1m-3 0V10m3 0V7.5m0 0a1.5 1.5 0 0 1 3 0v2m0 .5v-.5"
      />
    </Svg>
  );
}
