// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: hand-finger-2-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function HandFinger2Fill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M7 4.5a2.5 2.5 0 0 1 5 0v3.55a2.5 2.5 0 0 1 2.612 1.112a2.5 2.5 0 0 1 3 1A2.5 2.5 0 0 1 21 12.5v1.833q0 .093-.016.18A8 8 0 0 1 13 22h-.674a8 8 0 0 1-7.155-4.422l-3.065-6.13a1 1 0 0 1 .447-1.342c1.115-.558 2.194-.816 3.332-.342c.385.161.753.398 1.115.698z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
