// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: happy-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function HappyFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12S6.477 2 12 2m3.396 12.338a1 1 0 0 0-1.412-.088A3 3 0 0 1 12 15a3 3 0 0 1-1.983-.75a1.001 1.001 0 0 0-1.325 1.5A5 5 0 0 0 12 17a5 5 0 0 0 3.308-1.25c.414-.365.453-.998.088-1.412M8.5 8c-1.087 0-1.958.68-2.395 1.552a1.001 1.001 0 0 0 1.79.896c.162-.324.41-.448.605-.448s.443.124.605.448a1.001 1.001 0 0 0 1.79-.896C10.458 8.68 9.587 8 8.5 8m7 0c-1.087 0-1.958.68-2.395 1.552a1.001 1.001 0 0 0 1.79.896c.162-.324.41-.448.605-.448s.443.124.605.448a1.001 1.001 0 0 0 1.79-.896C17.458 8.68 16.587 8 15.5 8"
      />
    </Svg>
  );
}
