// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: happy-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function HappyLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M9.354 15c.705.622 1.632 1 2.646 1s1.94-.378 2.646-1M7 10c.3-.598.859-1 1.5-1s1.2.402 1.5 1m4 0c.3-.598.859-1 1.5-1s1.2.402 1.5 1m4 2a9 9 0 1 1-18 0a9 9 0 0 1 18 0Z"
      />
    </Svg>
  );
}
