// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: head-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function HeadFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M5 10a8 8 0 1 1 12 6.93v3.57a1.5 1.5 0 0 1-1.5 1.5h-4a1.5 1.5 0 0 1-1.5-1.5V19H8.766a3 3 0 0 1-2.977-2.628l-.14-1.123l-.747-.149a1.5 1.5 0 0 1-1.09-2.048l1.19-2.858z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
