// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: heading-2-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Heading2Fill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="3"
        d="M4 4v16m9-16v16m-9-8h9m3.64 3.357v-.094a1.663 1.663 0 0 1 2.407-1.488l.036.018a1.77 1.77 0 0 1 .927 2.014l-.007.026c-.074.297-.223.57-.431.794l-2.93 3.138l-.002.006v.22q0 .008.01.009h3.704"
      />
    </Svg>
  );
}
