// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: heavy-snow-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function HeavySnowLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M3.535 15a4.002 4.002 0 0 1 2.5-5.883a5.5 5.5 0 0 1 10.777-2.052A5 5 0 0 1 20 15.001M16 17v2m0 0v2m0-2l-1.732-1M16 19l1.732 1M16 19l-1.732 1M16 19l1.732-1M12 11v2m0 0v2m0-2l-1.732-1M12 13l1.732 1M12 13l-1.732 1M12 13l1.732-1M8 17v2m0 0v2m0-2l-1.732-1M8 19l1.732 1M8 19l-1.732 1M8 19l1.732-1"
      />
    </Svg>
  );
}
