// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: heavy-rain-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function HeavyRainFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M5 8.416a6.5 6.5 0 0 1 12.586-2.204a6.002 6.002 0 0 1 .344 11.471a3 3 0 0 0 .512-1.045l.26-.966a3 3 0 0 0-5.478-2.309a3 3 0 0 0-2.277-.16a3 3 0 0 0-5.375.917l-.259.965a3 3 0 0 0 0 1.553a3 3 0 0 0-.581.819A5 5 0 0 1 5 8.417"
      />
      <SvgPath
        fill={color}
        d="M8.729 13.93a1 1 0 0 1 .707 1.225l-.259.966a1 1 0 1 1-1.932-.518l.26-.966a1 1 0 0 1 1.224-.707m-1.035 3.864a1 1 0 0 1 .707 1.224l-.259.966a1 1 0 1 1-1.932-.517l.259-.966a1 1 0 0 1 1.225-.707m9.076-2.639a1 1 0 1 0-1.932-.518l-.259.966a1 1 0 1 0 1.932.518zm-1.036 3.863a1 1 0 0 0-1.931-.517l-.26.966a1 1 0 1 0 1.933.517zm-2.878-2.708a1 1 0 1 0-1.932-.518l-.259.966a1 1 0 1 0 1.932.518zm-1.036 3.864a1 1 0 0 0-1.931-.518l-.259.966a1 1 0 0 0 1.932.518z"
      />
    </Svg>
  );
}
