// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: hexagon-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function HexagonFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M10.75 2.33a2.5 2.5 0 0 1 2.5 0l6.5 3.752A2.5 2.5 0 0 1 21 8.247v7.506a2.5 2.5 0 0 1-1.25 2.165l-6.5 3.752a2.5 2.5 0 0 1-2.5 0l-6.5-3.753A2.5 2.5 0 0 1 3 15.753V8.247a2.5 2.5 0 0 1 1.25-2.165z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
