// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: hiking-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function HikingFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M16 21v-7.68l-1.696-.34a1 1 0 0 1-.511-.273L13 11.914v2.818l1.252 2.079c.138.229.229.484.267.749l.471 3.298a1 1 0 0 1-1.98.284l-.47-3.3l-1.006-1.666l-2.64 5.272a1.001 1.001 0 0 1-1.789-.896L10 14.772V9.5a1.5 1.5 0 0 1 2.911-.503l2.081 2.081L16 11.28V11a1 1 0 1 1 2 0v10a1 1 0 1 1-2 0M8.603 8.005A1 1 0 0 1 9.5 9v5a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1v-4a2 2 0 0 1 2-2zM15 5a3 3 0 1 1-6 0a3 3 0 0 1 6 0"
      />
    </Svg>
  );
}
