// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: home-5-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Home5Fill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M13.228 2.688a2 2 0 0 0-2.456 0l-8.384 6.52C1.636 9.795 2.05 11 3.003 11h1.092l.82 8.199a2 2 0 0 0 1.99 1.8h10.19a2 2 0 0 0 1.99-1.8l.82-8.2h1.092c.952 0 1.368-1.205.615-1.79zM12 16a3 3 0 1 0 0-6a3 3 0 0 0 0 6"
        clipRule="evenodd"
      />
    </Svg>
  );
}
