// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: home-7-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Home7Fill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M10.671 2.843a2 2 0 0 1 2.658 0l3.934 3.497l.25-1.504a1 1 0 0 1 1.973.328L19.03 7.91l2.635 2.342a1 1 0 0 1-1.328 1.495l-.464-.412l-.787 7.864a2 2 0 0 1-1.99 1.8H6.905a2 2 0 0 1-1.99-1.8l-.786-7.864l-.465.412a1 1 0 1 1-1.328-1.495z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
