// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: home-6-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Home6Line({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M12 14v6M5 10v9a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-9h1.997v-.002l-8.383-6.52a1 1 0 0 0-1.228 0l-8.384 6.52V10z"
      />
    </Svg>
  );
}
