// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: hospital-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function HospitalFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M5 2a2 2 0 0 0-2 2v16.9A1.1 1.1 0 0 0 4.1 22h15.8a1.1 1.1 0 0 0 1.1-1.1V11a2 2 0 0 0-2-2h-.5a.5.5 0 0 0-.5.5V20h-1V4a2 2 0 0 0-2-2zm5 3a1 1 0 0 0-1 1v1H8a1 1 0 0 0 0 2h1v1a1 1 0 1 0 2 0V9h1a1 1 0 1 0 0-2h-1V6a1 1 0 0 0-1-1m0 9a2 2 0 0 0-2 2v4h4v-4a2 2 0 0 0-2-2"
        clipRule="evenodd"
      />
    </Svg>
  );
}
