// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: idcard-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function IdcardLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath fill={color} d="M9 9.5a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0" />
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M11 14.5V14a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1v.5m8-3.5h2m-2 3h4M9 9.5a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0ZM4 19h16a1 1 0 0 0 1-1V6a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1Z"
      />
    </Svg>
  );
}
