// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: imac-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function ImacFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M5 3a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h4.966c-.114 1.634-.487 2.123-.545 2.189c-.446.343-.423.858-.339 1.115c.086.261.381.696.96.696h3.916c.579 0 .874-.435.96-.696c.084-.257.107-.772-.339-1.115c-.058-.066-.431-.555-.545-2.189H19a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2zm14 10v2H5v-2z"
      />
    </Svg>
  );
}
