// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: injection-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function InjectionLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="m12 4.929l7.071 7.07M10.586 9.17L12 10.585m-3.536.707l1.415 1.414m6.717-8.839l3.536 3.536m-.707-.707l-2.829 2.828m.707-4.95l-2.828 2.829m-6.718 8.839L3.93 20.07m9.485-13.728l4.243 4.243l-6.364 6.364a2 2 0 0 1-2.828 0L7.05 15.535a2 2 0 0 1 0-2.829z"
      />
    </Svg>
  );
}
