// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: intersect-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function IntersectFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M3 5a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v3h3a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2h-9a2 2 0 0 1-2-2v-3H5a2 2 0 0 1-2-2zm11 0v3h-4a2 2 0 0 0-2 2v4H5V5zm0 11h-4v3h9v-9h-3v4a2 2 0 0 1-2 2"
        clipRule="evenodd"
      />
    </Svg>
  );
}
