// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: key-1-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Key1Fill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M12 2a5 5 0 0 1 1 9.9V15h2a1 1 0 1 1 0 2h-2v1h2a1 1 0 1 1 0 2h-2v1a1 1 0 1 1-2 0v-9.1A5.001 5.001 0 0 1 12 2"
      />
    </Svg>
  );
}
