// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: key-3-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Key3Line({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M8 9V5.75a2.75 2.75 0 0 1 5.5 0V6M8 6a4 4 0 0 1 1.66 7.639L10 15l-.5 1l.5 1l-.5 1v.5a1.5 1.5 0 0 1-3 0v-4.793A4 4 0 0 1 8 6m11.531 5.483l-2-3.464a3.5 3.5 0 0 0-6.062 3.5l2 3.464a3.5 3.5 0 0 0 6.062-3.5"
      />
    </Svg>
  );
}
