// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: keyboard-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function KeyboardFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M4 4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2zm13 11a1 1 0 1 1 0 2H7a1 1 0 1 1 0-2zm0-4a1 1 0 1 1 0 2h-1a1 1 0 1 1 0-2zm-4.5 0a1 1 0 1 1 0 2h-1a1 1 0 1 1 0-2zM8 11a1 1 0 1 1 0 2H7a1 1 0 1 1 0-2zm9-4a1 1 0 1 1 0 2h-1a1 1 0 1 1 0-2zm-4.5 0a1 1 0 1 1 0 2h-1a1 1 0 1 1 0-2zM8 7a1 1 0 1 1 0 2H7a1 1 0 1 1 0-2z"
      />
    </Svg>
  );
}
