// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: knife-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function KnifeFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M3.294 20.37a1.237 1.237 0 0 1-.483-2.048L17.743 3.39a1.5 1.5 0 0 1 2.121 0l1.414 1.414a1.5 1.5 0 0 1 0 2.122l-4.596 4.596l1.928 1.928a1.25 1.25 0 0 1-.084 1.844L15.11 18.14a12.36 12.36 0 0 1-11.816 2.23"
        clipRule="evenodd"
      />
    </Svg>
  );
}
