// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: ladder-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function LadderFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        d="M17 1.5A1.5 1.5 0 0 1 18.5 3v18a1.5 1.5 0 0 1-3 0v-1.5h-7V21a1.5 1.5 0 0 1-3 0V3a1.5 1.5 0 1 1 3 0v1.5h7V3A1.5 1.5 0 0 1 17 1.5m-8.5 15h7v-1h-7zm0-4h7v-1h-7zm0-4h7v-1h-7z"
      />
    </Svg>
  );
}
