// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: laptop-2-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Laptop2Line({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinejoin="round"
        strokeWidth="2"
        d="M20 14V6a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v8m-1 2h18v1a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"
      />
    </Svg>
  );
}
