// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: large-arrow-left-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function LargeArrowLeftFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M20 8a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2h-8v2.793c0 1.336-1.616 2.006-2.56 1.06l-6.794-6.792a1.5 1.5 0 0 1 0-2.122l6.793-6.793C10.384 3.201 12 3.871 12 5.206V8z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
