// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: layout-grid-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function LayoutGridFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M11 21H5a2 2 0 0 1-2-2v-6h8zm10-2a2 2 0 0 1-2 2h-6v-8h8zM11 3v8H3V5a2 2 0 0 1 2-2zm8 0a2 2 0 0 1 2 2v6h-8V3z"
      />
    </Svg>
  );
}
