// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: left-small-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function LeftSmallFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M9.465 12.707a1 1 0 0 1 0-1.414l2.828-2.829A1 1 0 0 1 14 9.172v5.656a1 1 0 0 1-1.707.708z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
