// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: leo-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function LeoLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M10 15a3 3 0 1 1-6 0a3 3 0 0 1 6 0Zm0 0c.5-3-1-5-1-6.5a4.5 4.5 0 1 1 9 0c0 3-4 7-4 9.5a3 3 0 1 0 6 0"
      />
    </Svg>
  );
}
