// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: link-2-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Link2Fill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="3"
        d="m10.839 17.203l2.121 2.121a4.5 4.5 0 1 0 6.364-6.364l-2.121-2.121m-9.9 2.828l-2.121-2.121a4.5 4.5 0 1 1 6.364-6.364l2.121 2.121m-3.535 2.829l4.242 4.242"
      />
    </Svg>
  );
}
