// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: loading-3-fill · @iconify-json/mingcute v1.2.8
import { Svg, Circle as SvgCircle, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Loading3Fill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgCircle cx="12" cy="12" r="9" fill="none" stroke={color} strokeWidth="3" opacity=".1" />
      <SvgPath fill="none" stroke={color} strokeLinecap="round" strokeWidth="3" d="M12 3a8.96 8.96 0 0 0-6.225 2.5" />
    </Svg>
  );
}
