// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: magic-2-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Magic2Line({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="m6.044 6.05l2.122 2.122M10.994 11l9.192 9.192M15.944 6.05l-2.122 2.122m-5.656 5.656L6.044 15.95M17.994 11h-3m-8 0h-3m7 7v-3m0-8V4"
      />
    </Svg>
  );
}
