// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: magnet-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function MagnetLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="m16.02 17.78l-3.535-3.536m-2.828-2.829L6.12 7.88m12.73-2.83a7 7 0 0 1 0 9.9l-5.657 5.657a1 1 0 0 1-1.414 0l-2.121-2.122a1 1 0 0 1 0-1.414l5.657-5.657a2 2 0 1 0-2.829-2.828l-5.657 5.657a1 1 0 0 1-1.414 0l-2.121-2.122a1 1 0 0 1 0-1.414L8.95 5.051a7 7 0 0 1 9.9 0"
      />
    </Svg>
  );
}
