// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: mail-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function MailFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        d="M22 18a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V7.969l.36.3l8.68 7.232a1.5 1.5 0 0 0 1.92 0l8.68-7.232l.36-.3zM20 4a2 2 0 0 1 1.917 1.434l-1.558 1.298L12 13.698L3.64 6.732L2.083 5.434A2 2 0 0 1 4 4z"
      />
    </Svg>
  );
}
