// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: message-3-ai-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Message3AiLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M13 4h-2.5A7.5 7.5 0 0 0 3 11.5c0 6 4.5 9.5 9 9.5v-2h1.5a7.5 7.5 0 0 0 7.484-7M9 11.5a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0m7 0a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0M20 2l.13.378a4 4 0 0 0 2.492 2.493L23 5l-.378.13a4 4 0 0 0-2.493 2.492L20 8l-.13-.378a4 4 0 0 0-2.492-2.493L17 5l.378-.13a4 4 0 0 0 2.493-2.492z"
      />
    </Svg>
  );
}
