// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: mic-off-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function MicOffLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M12 19v2m0-2a7 7 0 0 1-6.93-6M12 19c.695 0 1.366-.101 2-.29M18.929 13a6.98 6.98 0 0 1-1.98 3.95M12 16a4 4 0 0 1-4-4M4.222 4.223L8 8m11.778 11.778L16.95 16.95M8 8V7a4 4 0 1 1 8 0v5a4 4 0 0 1-1.172 2.829M8 8l6.828 6.828m0 0l2.121 2.121"
      />
    </Svg>
  );
}
