// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: microphone-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function MicrophoneFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M14.185 5.302a7 7 0 0 1 1.529 6.656l3.401 4.372c.599.77.716 1.77.383 2.631a.83.83 0 0 0 .493-.014a1 1 0 0 1 .632 1.898a2.77 2.77 0 0 1-2.546-.39a2.7 2.7 0 0 1-2.75-.337l-4.373-3.4A7 7 0 0 1 4.3 15.19a21.4 21.4 0 0 0 5.766-4.117a21.4 21.4 0 0 0 4.119-5.77M4.044 5.047a7 7 0 0 1 8.548-1.055a19.4 19.4 0 0 1-3.94 5.667c-1.69 1.69-3.612 3-5.662 3.938a7 7 0 0 1 1.054-8.55"
      />
    </Svg>
  );
}
