// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: microscope-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function MicroscopeLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M4 21h16M5.782 14.596l2.122 2.121M12.5 21a5.5 5.5 0 0 0 2.781-10.246m0 0l1.815-1.815a1 1 0 0 0 0-1.414l-2.121-2.121a1 1 0 0 0-1.414 0L7.904 11.06a1 1 0 0 0 0 1.415l2.121 2.12a1 1 0 0 0 1.414 0zm1.815-3.23l1.414-1.413a1 1 0 0 0 0-1.415l-.707-.707a1 1 0 0 0-1.414 0l-1.414 1.415z"
      />
    </Svg>
  );
}
