// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: mingcute-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function MingcuteLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinejoin="round"
        strokeWidth="2"
        d="M9.16 7.281L4.076 4.972a.095.095 0 0 0-.134.081l-.773 14.38c-.003.07.067.12.132.093l5.463-2.307zm0 0l-.397 10.332L12 19.585l3.237-1.972l-.398-10.332m-5.678 0L12 8.464l2.839-1.183m0 0l5.085-2.309c.06-.027.13.015.134.081l.773 14.38a.095.095 0 0 1-.131.093l-5.464-2.307z"
      />
    </Svg>
  );
}
