// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: moai-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function MoaiFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M6.816 5.734A4 4 0 0 1 10.806 2h2.387a4 4 0 0 1 3.992 3.734l.084 1.268a1 1 0 0 1 1.062.931l.334 5a1 1 0 0 1-.93 1.065l.12 1.802a3 3 0 0 1-2.482 3.157l.576 1.727A1 1 0 0 1 15 22H9a1 1 0 0 1-.949-1.316l.576-1.727A3 3 0 0 1 6.144 15.8l.12-1.802a1 1 0 0 1-.929-1.064l.334-5a1 1 0 0 1 1.062-.932zm6.165 5.57a1 1 0 0 0-1.962 0l-.5 2.5A1 1 0 0 0 11.5 15h1a1 1 0 0 0 .98-1.196zM8.5 8a1 1 0 0 1 1-1h.5a1 1 0 1 1 0 2h-.5a1 1 0 0 1-1-1M14 7a1 1 0 1 0 0 2h.5a1 1 0 1 0 0-2z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
