// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: moderate-snow-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function ModerateSnowLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M4.354 16a4.002 4.002 0 0 1 1.68-6.883a5.5 5.5 0 0 1 10.777-2.052A5.001 5.001 0 0 1 19.001 16m-5-4v2m0 0v2m0-2l-1.733-1M14 14l1.732 1M14 14l-1.732 1M14 14l1.732-1M9 17v2m0 0v2m0-2l-1.732-1M9 19l1.732 1M9 19l-1.732 1M9 19l1.732-1"
      />
    </Svg>
  );
}
