// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: monument-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function MonumentLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M9 18V5L8 3l4-.5l4 .5l-1 2v13M4 21h16M6 21v-2.5a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 .5.5V21"
      />
    </Svg>
  );
}
