// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: monument-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function MonumentFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M11.876 1.508a1 1 0 0 1 .248 0l4 .5a1 1 0 0 1 .77 1.44L16 5.235V17h1.5a1.5 1.5 0 0 1 1.5 1.5V20h1a1 1 0 1 1 0 2H4a1 1 0 1 1 0-2h1v-1.5A1.5 1.5 0 0 1 6.5 17H8V5.236l-.894-1.789a1 1 0 0 1 .77-1.44z"
      />
    </Svg>
  );
}
