// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: moon-fog-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function MoonFogFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        d="M13.44 2.13a1 1 0 0 0-1.055 1.465a5 5 0 0 1-6.79 6.79A1 1 0 0 0 4.13 11.44a8 8 0 0 0 .641 1.989a1 1 0 0 0 .904.57h12.652a1 1 0 0 0 .904-.57a8.002 8.002 0 0 0-5.79-11.3M3 16a1 1 0 0 1 1-1h16a1 1 0 1 1 0 2H4a1 1 0 0 1-1-1m3 4a1 1 0 0 1 1-1h10a1 1 0 1 1 0 2H7a1 1 0 0 1-1-1"
      />
    </Svg>
  );
}
