// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: mountain-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function MountainLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M3 19h18M9 9l2 2l1-2l2 2l1-2m5 10s-4.136-7.353-5.8-13.247A1.025 1.025 0 0 0 13.22 5H13l-1 .25L11 5h-.22c-.458 0-.856.311-.98.753C8.135 11.647 4 19 4 19"
      />
    </Svg>
  );
}
