// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: mqtt-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function MqttLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M5 8.66A12.51 12.51 0 0 1 15.34 19M5 4c7.785 1.052 13.948 7.215 15 15M5 13.15A7.51 7.51 0 0 1 10.85 19H5zm11-9.145a23.6 23.6 0 0 1 4 4.002V4z"
      />
    </Svg>
  );
}
