// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: netease-music-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function NeteaseMusicLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M11.058 4c-4.135.457-7.351 4.162-7.351 8.73a8.27 8.27 0 0 0 13.784 6.164c4.01-3.588 1.378-10.55-2.757-10.55h-1.228A4.285 4.285 0 0 0 9.22 12.63a2.857 2.857 0 0 0 2.856 2.856h.13a2.986 2.986 0 0 0 2.986-2.986V5.796a1.796 1.796 0 0 1 3.29-.996l.386.578"
      />
    </Svg>
  );
}
