// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: paste-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function PasteLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M10 18H5a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h2m0 0v1a1 1 0 0 0 1 1h5a1 1 0 0 0 1-1V4M7 4a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1m0 0h2a1 1 0 0 1 1 1v5m2 0h-8a1 1 0 0 0-1 1v9a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-9a1 1 0 0 0-1-1"
      />
    </Svg>
  );
}
