// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: pencil-2-ai-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Pencil2AiLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M12 20h7m-14.925-.075l3.806-1.73a.5.5 0 0 0 .147-.102L18.924 7.197a1.5 1.5 0 1 0-2.121-2.122L5.907 15.971a.5.5 0 0 0-.102.147zM6 2l.13.378a4 4 0 0 0 2.492 2.493L9 5l-.378.13a4 4 0 0 0-2.493 2.492L6 8l-.13-.378a4 4 0 0 0-2.492-2.493L3 5l.378-.13a4 4 0 0 0 2.493-2.492z"
      />
    </Svg>
  );
}
