// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: pencil-2-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Pencil2Fill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M19 19a1 1 0 0 1 0 2h-7a1 1 0 1 1 0-2zM16.096 4.369a2.5 2.5 0 0 1 3.536 3.535L8.736 18.801q-.194.192-.44.304L4.49 20.834c-.842.383-1.707-.484-1.325-1.325l1.729-3.804q.113-.248.305-.44z"
      />
    </Svg>
  );
}
