// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: perplexity-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function PerplexityLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M12 3v18m-5.5-5H4V8.5h16V16h-2.5M12 8.5L6.5 14v6l5.5-5.5l5.5 5.5v-6zm0 0L6.5 4v4.5m5.5 0L17.5 4v4.5"
      />
    </Svg>
  );
}
