// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: photo-album-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function PhotoAlbumLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath fill={color} d="M17 11a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0" />
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="m15.857 16.655l1.59-1.591a.25.25 0 0 1 .355 0L21 18.262m-15 0l5.555-5.555a.25.25 0 0 1 .354 0l4.71 4.71M18 4H5a2 2 0 0 0-2 2v11m14-6a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0ZM7 20.333h13a1 1 0 0 0 1-1V8a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1v11.333a1 1 0 0 0 1 1Z"
      />
    </Svg>
  );
}
