// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: pig-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function PigLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M5 13a2 2 0 0 1-2-2v-.5m13 .5h.002M14 6l4-1v2.528A6 6 0 0 1 19.917 11H21v3l-1.726.863A6.03 6.03 0 0 1 17 17.197V19h-3v-1h-3v1H8v-1.803A6 6 0 0 1 11 6z"
      />
    </Svg>
  );
}
