// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: pinwheel-2-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Pinwheel2Line({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinejoin="round"
        strokeWidth="2"
        d="M12 12V3h-.5a4.5 4.5 0 0 0 0 9zm0 0h.5a4.5 4.5 0 1 1 0 9H12zm0 0H3v.5a4.5 4.5 0 1 0 9 0zm0 0v-.5a4.5 4.5 0 1 1 9 0v.5z"
      />
    </Svg>
  );
}
