// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: pinwheel-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function PinwheelLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinejoin="round"
        strokeWidth="2"
        d="M12 12V3S7.948 4.686 7 7c-.74 1.807 0 5 0 5zm0 0H3s1.686 4.052 4 5c1.807.74 5 0 5 0zm0 0v9s4.052-1.686 5-4c.74-1.807 0-5 0-5zm0 0h9s-1.686-4.052-4-5c-1.807-.74-5 0-5 0z"
      />
    </Svg>
  );
}
