// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: pisces-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function PiscesLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M7 20c1.266-2.31 2-5.055 2-8s-.734-5.69-2-8m10 0c-1.266 2.31-2 5.055-2 8s.734 5.69 2 8M6.022 11.979h12"
      />
    </Svg>
  );
}
