// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: play-circle-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function PlayCircleLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath fill="none" stroke={color} strokeLinejoin="round" strokeWidth="2" d="M21 12a9 9 0 1 1-18 0a9 9 0 0 1 18 0Z" />
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinejoin="round"
        strokeWidth="2"
        d="M9.99 8.52s1.253.488 3.018 1.506c1.764 1.02 2.813 1.86 2.813 1.86s-1.021.823-2.814 1.858s-3.016 1.508-3.016 1.508s-.205-1.32-.205-3.366s.205-3.366.205-3.366Z"
      />
    </Svg>
  );
}
