// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: presentation-1-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Presentation1Line({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="m8.46 21l3.535-3.535L15.532 21M3 4h18M8 12v1m4-3v3m4-5v5M4 4h16v12a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1z"
      />
    </Svg>
  );
}
