// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: presentation-3-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Presentation3Fill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M4 4.5A2.5 2.5 0 0 1 6.5 2h11A2.5 2.5 0 0 1 20 4.5v8a2.5 2.5 0 0 1-2.5 2.5h-11A2.5 2.5 0 0 1 4 12.5zM7 18l-1.8 2.4a1 1 0 0 0 1.6 1.2L9.5 18h5l2.7 3.6a1 1 0 0 0 1.6-1.2L17 18h3a1 1 0 1 0 0-2H4a1 1 0 1 0 0 2z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
