// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: print-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function PrintLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M17 18h3a1 1 0 0 0 1-1v-7a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v7a1 1 0 0 0 1 1h3m8-7h2M7 4h10v4H7zm0 11h10v6H7z"
      />
    </Svg>
  );
}
