// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: quote-left-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function QuoteLeftLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M5 14.5a2.5 2.5 0 1 0 5 0a2.5 2.5 0 0 0-5 0Zm0 0C4.833 13 5 10 9 7m5 7.5C13.833 13 14 10 18 7m-4 7.5a2.5 2.5 0 1 0 5 0a2.5 2.5 0 0 0-5 0Z"
      />
    </Svg>
  );
}
