// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: rada-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function RadaFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath fill={color} d="M13 12a1 1 0 1 1-2 0a1 1 0 0 1 2 0" />
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="3"
        d="M8.464 8.464A4.98 4.98 0 0 0 7 12c0 1.411.585 2.686 1.525 3.595m7.01-.06A4.98 4.98 0 0 0 17 12c0-1.364-.546-2.6-1.432-3.503M5.636 5.636A8.97 8.97 0 0 0 3 12a8.97 8.97 0 0 0 2.636 6.364M18.364 5.636A8.97 8.97 0 0 1 21 12a8.97 8.97 0 0 1-2.636 6.364M13 12a1 1 0 1 1-2 0a1 1 0 0 1 2 0Z"
      />
    </Svg>
  );
}
