// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: recycle-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function RecycleFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M10.268 2.5c.77-1.333 2.694-1.333 3.464 0l3.087 5.346a1.5 1.5 0 0 1 2.67 1.26l-.777 2.898a1.5 1.5 0 0 1-1.837 1.06l-2.898-.775a1.5 1.5 0 0 1 .244-2.943L12 5.5l-.965 1.67a1.5 1.5 0 1 1-2.598-1.5zm-2.92 5.935a1.5 1.5 0 0 1 1.838 1.06l.776 2.898a1.5 1.5 0 0 1-2.67 1.26L5.073 17.5H7a1.5 1.5 0 0 1 0 3H3.34c-1.54 0-2.502-1.667-1.732-3l3.087-5.346A1.5 1.5 0 0 1 4.45 9.21zm11.165 5.346a1.5 1.5 0 0 1 2.05.55l1.83 3.169c.77 1.333-.193 3-1.733 3h-6.173a1.5 1.5 0 0 1-2.426 1.682L9.94 20.061a1.5 1.5 0 0 1 0-2.122l2.12-2.121a1.5 1.5 0 0 1 2.427 1.682h4.441l-.964-1.67a1.5 1.5 0 0 1 .55-2.049"
        clipRule="evenodd"
      />
    </Svg>
  );
}
