// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: refresh-2-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Refresh2Fill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M1.498 12.083c-.01-1.314 1.45-2.04 2.492-1.337l2.678 1.805c1.463.986.486 3.268-1.238 2.89l-.108-.025a7.504 7.504 0 0 0 13.175.336a1.5 1.5 0 0 1 2.6 1.497c-2.317 4.02-7.119 6.152-11.815 4.894a10.5 10.5 0 0 1-7.784-10.06m1.406-5.331C5.22 2.733 10.022.6 14.718 1.858a10.5 10.5 0 0 1 7.784 10.061c.01 1.314-1.45 2.039-2.492 1.336l-2.678-1.804c-1.464-.986-.487-3.267 1.237-2.89l.108.024a7.48 7.48 0 0 0-4.736-3.83A7.505 7.505 0 0 0 5.503 8.25a1.5 1.5 0 0 1-2.599-1.498"
      />
    </Svg>
  );
}
