// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: refresh-3-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Refresh3Line({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M16.5 6H11a7 7 0 0 0-7 7v1M14.5 3.5L17 6l-2.5 2.5m-7 9.5H13a7 7 0 0 0 7-7v-1M9.5 20.5L7 18l2.5-2.5"
      />
    </Svg>
  );
}
