// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: refresh-4-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Refresh4Line({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M7.5 6H13a7 7 0 0 1 7 7v1M9.5 3.5L7 6l2.5 2.5m7 9.5H11a7 7 0 0 1-7-7v-1m10.5 10.5L17 18l-2.5-2.5"
      />
    </Svg>
  );
}
