// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: refresh-3-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Refresh3Fill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M13.382 4.5a1.5 1.5 0 0 1 2.179-2.06l2.5 2.5a1.5 1.5 0 0 1 0 2.12l-2.5 2.5a1.5 1.5 0 0 1-2.18-2.06H11A5.5 5.5 0 0 0 5.5 13a1.5 1.5 0 0 1-3 0A8.5 8.5 0 0 1 11 4.5zM5.91 16.969l.03-.03l2.5-2.5a1.5 1.5 0 0 1 2.178 2.061H13a5.5 5.5 0 0 0 5.5-5.5a1.5 1.5 0 0 1 3 0a8.5 8.5 0 0 1-8.5 8.5h-2.382a1.5 1.5 0 0 1-2.179 2.06l-2.5-2.5a1.5 1.5 0 0 1-.439-1.046"
      />
    </Svg>
  );
}
