// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: refresh-anticlockwise-1-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function RefreshAnticlockwise1Line({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="m4.04 10.41l1.708-.382c.108-.024.17.12.077.181L3.152 12.01a.098.098 0 0 1-.154-.081q.004-.588.085-1.163a9.003 9.003 0 0 1 17.61-1.096A9 9 0 0 1 4.513 17"
      />
    </Svg>
  );
}
