// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: repeat-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function RepeatLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M4 14V8a2 2 0 0 1 2-2h12m2 4v6a2 2 0 0 1-2 2H6"
      />
      <SvgPath
        fill={color}
        d="M16.578 3.654c-.28-.146-.604.065-.631.411a25 25 0 0 0-.073 1.93c0 .848.04 1.538.078 1.996c.027.324.323.503.598.36a19 19 0 0 0 1.55-.91a20 20 0 0 0 1.476-1.056c.248-.196.259-.574.023-.762a19 19 0 0 0-1.498-1.074a19 19 0 0 0-1.523-.895m-9.162 12c.28-.146.604.065.632.411a25.4 25.4 0 0 1-.006 3.926c-.026.324-.323.503-.598.36a19 19 0 0 1-1.55-.91a20 20 0 0 1-1.476-1.056c-.248-.196-.258-.574-.023-.762a20 20 0 0 1 1.499-1.074a19 19 0 0 1 1.522-.895"
      />
    </Svg>
  );
}
