// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: rest-area-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function RestAreaFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M8 2a3 3 0 1 0 0 6a3 3 0 0 0 0-6m8 0a3 3 0 1 0 0 6a3 3 0 0 0 0-6M4.103 11.181A2 2 0 0 1 6.095 9h3.81a2 2 0 0 1 1.992 2.181l-.901 9.91A1 1 0 0 1 10 22H6a1 1 0 0 1-.996-.91zM14.82 9a2 2 0 0 0-1.961 1.608l-.84 4.196A1 1 0 0 0 13 16v5a1 1 0 0 0 1 1h4a1 1 0 0 0 1-1v-5a1 1 0 0 0 .98-1.196l-.839-4.196A2 2 0 0 0 17.181 9z"
      />
    </Svg>
  );
}
