// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: rewind-backward-30-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function RewindBackward30Line({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="m7.214 9.51l.012-.028A1.61 1.61 0 0 1 8.71 8.5h.07a1.72 1.72 0 0 1 1.211 2.942l-.106.105a1.56 1.56 0 0 1-1.1.453m-1.57 2.428l.011.027c.253.596.837.982 1.484.982h.094a1.696 1.696 0 0 0 1.152-2.94l-.228-.212A1.07 1.07 0 0 0 9 12m-6-.003a9 9 0 0 0 7.024 8.758a9 9 0 1 0 3.957-17.56a9 9 0 0 0-8.987 3.13L5.5 2l.502 2.502M15 15.5a1.5 1.5 0 0 1-1.5-1.5v-4a1.5 1.5 0 0 1 3 0v4a1.5 1.5 0 0 1-1.5 1.5"
      />
    </Svg>
  );
}
