// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: rewind-forward-square-5-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function RewindForwardSquare5Line({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M13.763 8.5h-3.5v3.063s.875-.438 1.75-.438c1.313 0 2.188.98 2.188 2.188a2.187 2.187 0 0 1-4.193.874M21 11v5a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3V8a3 3 0 0 1 3-3h13l-2.5-2.5l1 2"
      />
    </Svg>
  );
}
