// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: riding-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function RidingFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M6 13a4 4 0 1 1 0 8a4 4 0 0 1 0-8m12 0a4 4 0 1 1 0 8a4 4 0 0 1 0-8m-6.01-5.444a1.5 1.5 0 0 1 1.94-.03l.108.098L16.414 10H18a1 1 0 1 1 0 2h-1.793a1.5 1.5 0 0 1-1.06-.44l-1.193-1.192l-2.633 2.304l1.318 1.537a1.5 1.5 0 0 1 .361.976V19a1 1 0 1 1-2 0v-3.63l-2.437-2.844a1.5 1.5 0 0 1 .15-2.104zM16 3a2 2 0 1 1 0 4a2 2 0 0 1 0-4"
      />
    </Svg>
  );
}
