// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: right-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function RightLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M9.343 6.343L15 12l-5.657 5.657"
      />
    </Svg>
  );
}
