// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: round-line · @iconify-json/mingcute v1.2.8
import { Svg, Circle as SvgCircle } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function RoundLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgCircle cx="12" cy="12" r="9" fill="none" stroke={color} strokeWidth="2" />
    </Svg>
  );
}
