// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: route-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function RouteFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M18 16a3 3 0 1 0 0 6a3 3 0 0 0 0-6M11 4a1 1 0 1 0 0 2h4.5a2.5 2.5 0 0 1 0 5h-7a4.5 4.5 0 1 0 0 9H13a1 1 0 1 0 0-2H8.5a2.5 2.5 0 0 1 0-5h7a4.5 4.5 0 1 0 0-9zM6 2a3 3 0 1 0 0 6a3 3 0 0 0 0-6"
      />
    </Svg>
  );
}
