// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: route-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function RouteLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M11 5h4.5a3.5 3.5 0 1 1 0 7h-7a3.5 3.5 0 1 0 0 7H13M8 5a2 2 0 1 1-4 0a2 2 0 0 1 4 0Zm12 14a2 2 0 1 1-4 0a2 2 0 0 1 4 0Z"
      />
    </Svg>
  );
}
