// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: run-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function RunFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M10 5a3 3 0 1 1 3.469 2.964l1.436 2.297l1.724-.69a1 1 0 0 1 .742 1.858l-2.111.844a1.5 1.5 0 0 1-1.83-.598l-.406-.65l-.611 2.476a2 2 0 0 1-.33.701l1.664 1.236a2 2 0 0 1 .795 1.384L14.895 20H15a1 1 0 1 1 0 2h-1a1 1 0 0 1-.994-.89l-.452-4.067l-3.15-2.34c-.66-.49-1.018-1.336-.818-2.146l.796-3.228l-1.597.48l-.836 2.507a1 1 0 1 1-1.898-.632l.836-2.508A2 2 0 0 1 7.21 7.893l3.437-1.031A3 3 0 0 1 10 5m-.4 10.2a1 1 0 0 1 .2 1.4l-1.216 1.622a1.5 1.5 0 0 1-2.032.348l-1.93-1.287a1 1 0 0 1-1.33-1.49l.5-.5a1 1 0 0 1 1.263-.125l2.213 1.475L8.2 15.4a1 1 0 0 1 1.4-.2"
        clipRule="evenodd"
      />
    </Svg>
  );
}
