// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: scissors-3-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Scissors3Fill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="m22.414 16.862l-.287.409a2.5 2.5 0 0 1-3.482.614l-5.79-4.054l-1.784 1.25a4.5 4.5 0 1 1-2.155-2.153L10.24 12l-1.324-.927a4.5 4.5 0 1 1 2.155-2.153l1.784 1.249l5.79-4.054a2.5 2.5 0 0 1 3.482.614l.287.41L15.47 12zM8.5 7a1.5 1.5 0 1 0-3 0a1.5 1.5 0 0 0 3 0m0 10a1.5 1.5 0 1 0-3 0a1.5 1.5 0 0 0 3 0"
        clipRule="evenodd"
      />
      <SvgPath
        fill="none"
        stroke={color}
        d="M3.5 12a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0Zm4 0a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0Zm11 0a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0Zm3 0a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0Z"
      />
    </Svg>
  );
}
