// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: search-3-ai-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Search3AiLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M14.5 14.5L20 20m-4-10a6 6 0 1 1-12 0a6 6 0 0 1 12 0Z"
      />
      <SvgPath
        fill={color}
        d="M9.88 7.19c.113-.253.113-.253.224 0l.11.241a5.64 5.64 0 0 0 2.306 2.466c.18.103.181.103 0 .206l-.172.1a5.64 5.64 0 0 0-2.244 2.607c-.111.253-.111.253-.223 0a5.64 5.64 0 0 0-2.415-2.707c-.182-.103-.181-.104 0-.206l.172-.1A5.64 5.64 0 0 0 9.88 7.19m8.036-5.064c.084-.168.084-.168.168 0q.04.081.083.162a3.96 3.96 0 0 0 1.73 1.644c.137.068.137.068 0 .137l-.127.066a3.96 3.96 0 0 0-1.686 1.739c-.084.168-.084.168-.168 0l-.083-.162a3.96 3.96 0 0 0-1.73-1.643c-.137-.069-.137-.069 0-.137l.127-.067a3.96 3.96 0 0 0 1.686-1.739"
      />
    </Svg>
  );
}
