// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: search-2-none-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Search2NoneFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M10 3a7 7 0 0 1 5.605 11.191l5.102 5.102a1 1 0 1 1-1.414 1.414l-5.102-5.102A7 7 0 1 1 10 3m2.475 4.525a1 1 0 0 0-1.415 0L10 8.585l-1.06-1.06A1 1 0 0 0 7.524 8.94L8.585 10l-1.06 1.06a1 1 0 0 0 1.414 1.415L10 11.415l1.06 1.06a1 1 0 0 0 1.415-1.415L11.415 10l1.06-1.06a1 1 0 0 0 0-1.415"
      />
    </Svg>
  );
}
