// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: selector-horizontal-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function SelectorHorizontalFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M7.293 12.707a1 1 0 0 1 0-1.414l2-2A1 1 0 0 1 11 10v4a1 1 0 0 1-1.707.707zm9.414 0a1 1 0 0 0 0-1.414l-2-2A1 1 0 0 0 13 10v4a1 1 0 0 0 1.707.707z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
