// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: send-plane-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function SendPlaneFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M21.432 4.862a1 1 0 0 0-1.181-1.33l-17.5 4.5a1 1 0 0 0-.443 1.691l5.193 4.965v4.52a.5.5 0 0 0 .853.353l2.073-2.073l3.381 3.235a1 1 0 0 0 1.624-.361zM9.768 14.813l-1.735-1.66L19 6z"
      />
    </Svg>
  );
}
