// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: settings-2-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Settings2Fill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M17 2.5A1.5 1.5 0 0 1 18.5 4v.5H20a1.5 1.5 0 0 1 0 3h-1.5V8a1.5 1.5 0 0 1-3 0v-.5H4a1.5 1.5 0 1 1 0-3h11.5V4A1.5 1.5 0 0 1 17 2.5m-10 6A1.5 1.5 0 0 1 8.5 10v.5H20a1.5 1.5 0 0 1 0 3H8.5v.5a1.5 1.5 0 0 1-3 0v-.5H4a1.5 1.5 0 0 1 0-3h1.5V10A1.5 1.5 0 0 1 7 8.5m10 6a1.5 1.5 0 0 1 1.5 1.5v.5H20a1.5 1.5 0 0 1 0 3h-1.5v.5a1.5 1.5 0 0 1-3 0v-.5H4a1.5 1.5 0 0 1 0-3h11.5V16a1.5 1.5 0 0 1 1.5-1.5"
        clipRule="evenodd"
      />
    </Svg>
  );
}
