// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: share-2-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Share2Fill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M15 5.5a3.5 3.5 0 1 1 1.136 2.581l-4.401 2.308c.172.505.265 1.047.265 1.611c0 .563-.093 1.105-.265 1.61l4.402 2.308a3.5 3.5 0 1 1-1.03 1.719l-4.384-2.299a5 5 0 1 1 0-6.677l4.384-2.298A3.5 3.5 0 0 1 15 5.5"
        clipRule="evenodd"
      />
    </Svg>
  );
}
