// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: shopping-cart-1-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function ShoppingCart1Line({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath fill={color} d="M8 20.5a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0m10 0a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0" />
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M3 3h.138a2 2 0 0 1 1.995 1.858l.8 11.213a1 1 0 0 0 .998.929h11.234a1 1 0 0 0 .984-.821l1.637-9A1 1 0 0 0 19.802 6H6m2 14.5a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0m10 0a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0"
      />
    </Svg>
  );
}
