// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: showers-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function ShowersFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M5 8.416a6.5 6.5 0 0 1 12.586-2.204a6.002 6.002 0 0 1-1.172 11.774l-.001-.003c.36-.36.634-.817.776-1.345l.259-.966a3 3 0 0 0-5.664-1.94a3 3 0 0 0-4.802 1.543l-.258.966a3 3 0 0 0-.001 1.552a3 3 0 0 0-.172.187a5 5 0 0 1-1.55-9.564"
      />
      <SvgPath
        fill={color}
        d="M14.809 13.93a1 1 0 0 1 .707 1.225l-.26.966a1 1 0 0 1-1.931-.518l.259-.966a1 1 0 0 1 1.225-.707m-1.036 3.864a1 1 0 0 1 .707 1.224l-.258.966a1 1 0 1 1-1.932-.517l.259-.966a1 1 0 0 1 1.224-.707m-3.634-2.709a1 1 0 0 1 .707 1.225l-.259.966a1 1 0 0 1-1.932-.518l.26-.966a1 1 0 0 1 1.224-.707m-1.035 3.864a1 1 0 0 1 .707 1.224l-.26.967a1 1 0 0 1-1.931-.518l.259-.966a1 1 0 0 1 1.225-.707"
      />
    </Svg>
  );
}
