// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: shuffle-2-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Shuffle2Line({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M4 7h2.301a3 3 0 0 1 2.573 1.457l4.252 7.086A3 3 0 0 0 15.7 17H18M4 17h2.301a3 3 0 0 0 2.573-1.457L9.5 14.5M18 7h-2.301a3 3 0 0 0-2.573 1.457L12.5 9.5"
      />
      <SvgPath
        fill={color}
        d="M17.579 4.654c-.28-.146-.605.065-.632.411a25 25 0 0 0-.072 1.93c0 .848.04 1.538.077 1.996c.027.324.323.503.599.36c.368-.192.905-.492 1.55-.91a20 20 0 0 0 1.476-1.056c.247-.196.258-.574.022-.762a19 19 0 0 0-1.498-1.074a19 19 0 0 0-1.523-.895m.001 10c-.28-.146-.605.065-.632.411a25 25 0 0 0-.072 1.93c0 .848.04 1.538.077 1.996c.027.324.323.503.599.36c.368-.192.905-.492 1.55-.91a20 20 0 0 0 1.476-1.056c.247-.196.258-.574.022-.762a19 19 0 0 0-1.498-1.074a19 19 0 0 0-1.523-.895"
      />
    </Svg>
  );
}
