// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: skip-forward-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function SkipForwardFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        d="M3.569 5.863A1.332 1.332 0 0 1 5.414 4.8c.848.36 2.88 1.271 5.479 2.771s4.404 2.806 5.14 3.36c.71.536.71 1.594 0 2.13c-.728.55-2.51 1.838-5.141 3.357s-4.639 2.419-5.48 2.775a1.332 1.332 0 0 1-1.843-1.065c-.113-.911-.341-3.12-.341-6.133c0-3.01.228-5.218.34-6.13M19 5a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1h-1a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1z"
      />
    </Svg>
  );
}
