// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: skip-previous-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function SkipPreviousLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M5 6v12m13.772-6.004c0 2.967-.225 5.135-.333 6.013a.33.33 0 0 1-.46.265c-.808-.342-2.778-1.224-5.37-2.721c-2.593-1.496-4.342-2.762-5.042-3.29a.33.33 0 0 1 0-.531c.709-.534 2.481-1.816 5.04-3.294s4.555-2.371 5.372-2.718a.33.33 0 0 1 .46.266c.109.878.333 3.045.333 6.01"
      />
    </Svg>
  );
}
