// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: skull-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function SkullFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M12 2a9 9 0 0 1 5.499 16.125c-.338.262-.499.59-.499.875a2 2 0 0 1-2 2v-1a1 1 0 1 0-2 0v1h-2v-1a1 1 0 1 0-2 0v1a2 2 0 0 1-2-2c0-.284-.16-.613-.499-.875A9 9 0 0 1 12 2m-1 9.5a2.5 2.5 0 1 1-5 0a2.5 2.5 0 0 1 5 0m4.5 2.5a2.5 2.5 0 1 0 0-5a2.5 2.5 0 0 0 0 5"
        clipRule="evenodd"
      />
    </Svg>
  );
}
