// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: solar-panel-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function SolarPanelFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M10.105 4h3.79l.5 5h-4.79zm-.7 7h5.19l.5 5H13v2h2a1 1 0 1 1 0 2H9a1 1 0 1 1 0-2h2v-2H8.905zm7.2 0l.5 5h3.285a1.5 1.5 0 0 0 1.471-1.794L21.22 11zm-.7-7l.5 5h4.415l-.679-3.392A2 2 0 0 0 18.181 4zm-7.81 0H5.82a2 2 0 0 0-1.961 1.608L3.18 9h4.415zm-.7 7H2.78l-.641 3.206A1.5 1.5 0 0 0 3.609 16h3.286z"
      />
    </Svg>
  );
}
