// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: solana-sol-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function SolanaSolLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinejoin="round"
        strokeWidth="2"
        d="M8 5h13l-3 3H5zM7 17h13l-3 3H4zm-2-6h13l2 3H7z"
      />
    </Svg>
  );
}
