// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: solana-sol-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function SolanaSolFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M7.293 4.293A1 1 0 0 1 8 4h13a1 1 0 0 1 .707 1.707l-3 3A1 1 0 0 1 18 9H5a1 1 0 0 1-.707-1.707zm-3.175 6.235A1 1 0 0 1 5 10h13a1 1 0 0 1 .832.445l2 3A1 1 0 0 1 20 15H7a1 1 0 0 1-.832-.445l-2-3a1 1 0 0 1-.05-1.027m2.175 5.765A1 1 0 0 1 7 16h13a1 1 0 0 1 .707 1.707l-3 3A1 1 0 0 1 17 21H4a1 1 0 0 1-.707-1.707z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
