// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: soup-pot-2-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function SoupPot2Fill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M10 3a1 1 0 0 0 0 2h1v1h-1a6 6 0 0 0-.713.055c-.415.053-.99.158-1.65.366A9.5 9.5 0 0 0 4.506 8.1a2 2 0 0 0-.093-.1l-.707-.707a1 1 0 0 0-1.414 1.414L3 9.414V16a5 5 0 0 0 5 5h8a5 5 0 0 0 5-5V9.414l.707-.707a1 1 0 0 0-1.414-1.414L19.586 8a2 2 0 0 0-.092.099a9.5 9.5 0 0 0-3.13-1.678a9.5 9.5 0 0 0-1.651-.366A8 8 0 0 0 14 6h-1V5h1a1 1 0 1 0 0-2z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
