// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: spacing-horizontal-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function SpacingHorizontalFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="3"
        d="M4 4h2a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H4M20 4h-2a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h2M12 8v8"
      />
    </Svg>
  );
}
