// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: stock-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function StockFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M8 2a1 1 0 0 1 1 1v2a3 3 0 0 1 3 3v6a3 3 0 0 1-3 3v4a1 1 0 1 1-2 0v-4a3 3 0 0 1-3-3V8a3 3 0 0 1 3-3V3a1 1 0 0 1 1-1m10 19a1 1 0 1 1-2 0v-2a3 3 0 0 1-3-3v-6a3 3 0 0 1 3-3V3a1 1 0 1 1 2 0v4a3 3 0 0 1 3 3v6a3 3 0 0 1-3 3z"
      />
    </Svg>
  );
}
