// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: sun-fog-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function SunFogFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        d="M12 2a1 1 0 0 1 1 1v1a1 1 0 1 1-2 0V3a1 1 0 0 1 1-1M4 15a1 1 0 1 0 0 2h16a1 1 0 1 0 0-2zm3 4a1 1 0 1 0 0 2h10a1 1 0 1 0 0-2zM18.364 7.05l.707-.707a1 1 0 0 0-1.414-1.414l-.707.707a1 1 0 0 0 1.414 1.414M22 12a1 1 0 0 1-1 1h-1a1 1 0 1 1 0-2h1a1 1 0 0 1 1 1M4 13a1 1 0 1 0 0-2H3a1 1 0 1 0 0 2zm1.636-5.95l-.707-.707A1 1 0 1 1 6.343 4.93l.707.707A1 1 0 0 1 5.636 7.05M12 6a6 6 0 0 0-5.88 7.2a1 1 0 0 0 .98.8h9.8a1 1 0 0 0 .98-.8q.12-.585.12-1.2a6 6 0 0 0-6-6"
      />
    </Svg>
  );
}
