// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: sun-2-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function Sun2Line({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M3 9h8.5a1.5 1.5 0 0 1 0 3h-2a1.5 1.5 0 0 0 0 3H21m-1-3a8 8 0 1 1-16 0a8 8 0 0 1 16 0"
      />
    </Svg>
  );
}
