// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: switch-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function SwitchFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M16.5 12a4.5 4.5 0 1 1 0 9h-9a4.5 4.5 0 1 1 0-9zM7 14.5a2 2 0 1 0 0 4a2 2 0 0 0 0-4M16.5 2a4.5 4.5 0 1 1 0 9h-9a4.5 4.5 0 0 1 0-9zm.5 2.5a2 2 0 1 0 0 4a2 2 0 0 0 0-4"
      />
    </Svg>
  );
}
