// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: sword-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function SwordFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M19.071 3.928a1 1 0 0 1 1 1v5.657a1 1 0 0 1-.406.804l-7.197 5.32l.946.947a1 1 0 0 1 0 1.414L12 20.485a1 1 0 0 1-1.154.187L8.662 19.58L7.05 21.192a1 1 0 0 1-1.414 0l-2.828-2.829a1 1 0 0 1 0-1.414l1.611-1.612l-1.092-2.183a1 1 0 0 1 .188-1.155l1.414-1.414a1 1 0 0 1 1.414 0l.947.947l5.32-7.198a1 1 0 0 1 .804-.406z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
