// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: telegram-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function TelegramLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="m15.5 11.5l-5 4.5m-.056.167c.777 1.348 4.693 3.598 6.711 4.694a.976.976 0 0 0 1.429-.71l2.269-13.757a.5.5 0 0 0-.688-.543l-17.1 7.2a.486.486 0 0 0-.004.901c1.835.76 5.578 2.215 7.383 2.215"
      />
    </Svg>
  );
}
