// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: test-tube-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function TestTubeFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M7 3a1 1 0 0 1 1-1h8a1 1 0 1 1 0 2v14a4 4 0 0 1-8 0V4a1 1 0 0 1-1-1m5 4a1 1 0 1 0 0 2h2V7zm-1 5a1 1 0 0 1 1-1h2v2h-2a1 1 0 0 1-1-1m1 3a1 1 0 1 0 0 2h2v-2z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
