// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: textbox-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function TextboxLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M11 3a1 1 0 1 0 0 2zm0 16a1 1 0 1 0 0 2zm6-14a1 1 0 1 0 0-2zm0 16a1 1 0 1 0 0-2zM11 4v1h.99V3H11zm2.99 2h-1v12h2V6zm-2 14v-1H11v2h.99zM17 4V3h-1v2h1zm-3 2h-1v12h2V6zm2 14v1h1v-2h-1zm4-11h-1v6h2V9zM4 15h1V9H3v6zm1-7v1h7V7H5zm11 0v1h3V7h-3zm-4 8v-1H5v2h7zm7 0v-1h-3v2h3zM4 9h1V7a2 2 0 0 0-2 2zm0 6H3a2 2 0 0 0 2 2v-2zm16 0h-1v2a2 2 0 0 0 2-2zm0-6h1a2 2 0 0 0-2-2v2zm-4-5V3a3 3 0 0 0-3 3h2a1 1 0 0 1 1-1zm-2.01 14h-1a1 1 0 0 1-1 1v2a3 3 0 0 0 3-3zm.01 0h-1a3 3 0 0 0 3 3v-2a1 1 0 0 1-1-1zM11.99 4v1a1 1 0 0 1 1 1h2a3 3 0 0 0-3-3z"
      />
    </Svg>
  );
}
