// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: toggle-left-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function ToggleLeftLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeWidth="2"
        d="M7 17h10a5 5 0 0 0 0-10H7m0 10A5 5 0 0 0 7 7m0 10a5 5 0 0 1-5-5m5 5a5 5 0 0 1-5-5m0 0a5 5 0 0 1 5-5m-5 5a5 5 0 0 1 5-5"
      />
    </Svg>
  );
}
