// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: toxophily-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function ToxophilyLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="m10 3l1 1m0 0l1.858 1.239a4 4 0 0 1 1.576 2.063L16 12l-1.566 4.698a4 4 0 0 1-1.576 2.063L11 20m0-16l-5 8l5 8m0 0l-1 1m-5-9h14m0-1l1 1l-1 1z"
      />
    </Svg>
  );
}
