// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: traffic-lights-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function TrafficLightsFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M14 2a4 4 0 0 1 4 4v12a4 4 0 0 1-4 4h-4a4 4 0 0 1-4-4V6a4 4 0 0 1 4-4zm-2 13a2 2 0 1 0 0 4a2 2 0 0 0 0-4m0-5a2 2 0 1 0 0 4a2 2 0 0 0 0-4m0-5a2 2 0 1 0 0 4a2 2 0 0 0 0-4"
      />
    </Svg>
  );
}
