// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: trouser-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function TrouserFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M19.994 20.89A1 1 0 0 1 19 22h-5a1 1 0 0 1-.976-.783L12 16.609l-1.023 4.608A1 1 0 0 1 10 22H5a1 1 0 0 1-.994-1.11L5.55 7h12.9zM16.104 2a2 2 0 0 1 1.989 1.78L18.229 5H5.772l.135-1.22A2 2 0 0 1 7.896 2z"
      />
    </Svg>
  );
}
