// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: ubuntu-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function UbuntuLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M5.563 7.25a8 8 0 0 1 5.541-3.2m8.23 4.75c.428.98.666 2.063.666 3.2s-.238 2.22-.666 3.2m-8.23 4.75a8 8 0 0 1-5.541-3.199M6 12.001a2 2 0 1 1-4 0a2 2 0 0 1 4 0Zm9-5.197a2 2 0 1 1 2-3.464a2 2 0 0 1-2 3.464Zm0 10.392a2 2 0 1 1 2 3.464a2 2 0 0 1-2-3.464Z"
      />
    </Svg>
  );
}
