// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: umbrella-2-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Umbrella2Line({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M4 20.001h16M16 5.073A8 8 0 0 0 5.624 7.168c-.333.44-.164 1.057.314 1.333l12.124 7c.479.277 1.097.114 1.312-.395A8 8 0 0 0 16 5.073m0 0c-1.435-.828-4.389 1.602-6.598 5.428l5.196 3c2.21-3.826 2.837-7.6 1.402-8.428m0 0l.5-.866M12 12l-4.5 8"
      />
    </Svg>
  );
}
