// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: unlink-2-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Unlink2Line({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="m10.585 16.949l2.122 2.121a4.5 4.5 0 1 0 6.364-6.364l-2.122-2.121m-9.9 2.828l-2.12-2.121a4.5 4.5 0 1 1 6.364-6.364l2.12 2.121M9.879 9.878l4.243 4.243M16 3v2M8 19v2M19 7h1M4 17h1"
      />
    </Svg>
  );
}
