// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: usb-flash-disk-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function UsbFlashDiskLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinejoin="round"
        strokeWidth="2"
        d="M9 6h2m2 0h2M5 9h14v7a4 4 0 0 1-4 4H9a4 4 0 0 1-4-4zm12 0V4a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v5z"
      />
    </Svg>
  );
}
