// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: usb-flash-disk-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function UsbFlashDiskFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill={color}
        d="M16 2a2 2 0 0 1 2 2v4h1a1 1 0 0 1 1 1v7a5 5 0 0 1-5 5H9a5 5 0 0 1-5-5V9a1 1 0 0 1 1-1h1V4a2 2 0 0 1 2-2zM8 8h8V4H8zm3-1H9V5h2zm4 0h-2V5h2z"
      />
    </Svg>
  );
}
