// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: user-x-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function UserXLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M12.21 14.064A12 12 0 0 0 11 14c-4.418 0-8 2.567-8 4.5S6.582 21 11 21q.339 0 .672-.005m8.45-5.116L18 18m0 0l-2.121 2.122M18 18l-2.12-2.12M18 18l2.121 2.122M15 7a4 4 0 1 1-8 0a4 4 0 0 1 8 0Z"
      />
    </Svg>
  );
}
