// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: user-remove-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function UserRemoveLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2m14-10h4m-6-4a4 4 0 1 1-8 0a4 4 0 0 1 8 0Z"
      />
    </Svg>
  );
}
