// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: vector-bezier-2-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function VectorBezier2Line({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeWidth="2"
        d="M8 5h7m0 0a1 1 0 1 0 2 0a1 1 0 0 0-2 0ZM9 19h7m-7 0a1 1 0 1 1-2 0a1 1 0 0 1 2 0ZM8 5.341c2.33.824 4 3.047 4 5.659v2a6 6 0 0 0 4 5.659M8 5.34V4a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1zm8 13.318V20a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1h-2a1 1 0 0 0-1 1z"
      />
    </Svg>
  );
}
