// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: vector-bezier-2-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function VectorBezier2Fill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M3 4a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2h5.268A2 2 0 0 1 18 5a2 2 0 0 1-3.732 1h-3.37A6.98 6.98 0 0 1 13 11v2a5 5 0 0 0 2.194 4.14A2 2 0 0 1 17 16h2a2 2 0 0 1 2 2v2a2 2 0 0 1-2 2h-2a2 2 0 0 1-2-2H9.732a2 2 0 1 1 0-2h3.37A6.98 6.98 0 0 1 11 13v-2a5 5 0 0 0-2.194-4.14A2 2 0 0 1 7 8H5a2 2 0 0 1-2-2z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
