// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: video-camera-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function VideoCameraLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeWidth="2"
        d="M3 12a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2zm14 2l3.238-1.995a.5.5 0 0 1 .762.426v5.138a.5.5 0 0 1-.762.425L17 16z"
      />
      <SvgPath
        fill="none"
        stroke={color}
        strokeWidth="2"
        d="M15 7a3 3 0 1 1-6 0a3 3 0 0 1 6 0Zm-6 .5a2.5 2.5 0 1 1-5 0a2.5 2.5 0 0 1 5 0Z"
      />
    </Svg>
  );
}
