// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: vip-4-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Vip4Fill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M11.2 1.4a1 1 0 0 1 1.601 0l2.7 3.6h4.644a1.5 1.5 0 0 1 1.308 2.235l-8.364 14.868c-.478.85-1.7.85-2.178 0L2.547 7.235a1.5 1.5 0 0 1 1.308-2.236H8.5zM9.33 7.223l2.666 4.444l2.668-4.444l-2.668-3.556z"
      />
    </Svg>
  );
}
