// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: visa-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function VisaFill({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="3"
        d="M3 8h1v8l3-8m3 0l-1 8m6.373-7c.127-.5-.173-1-.873-1h-.176a1.5 1.5 0 0 0-1.488 1.314l-.114.907A1.7 1.7 0 0 0 13.751 12a1.7 1.7 0 0 1 1.028 1.78l-.114.907A1.5 1.5 0 0 1 13.177 16H13c-.792 0-.959-.325-.873-1M17 16l3-8l1 8m-3.25-2h3"
      />
    </Svg>
  );
}
