// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: vscode-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function VscodeLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinejoin="round"
        strokeWidth="2"
        d="M9.004 10.276L16 3l4 3v12l-4 3l-6.996-7.276M16 3v18m0-18v5l-4.889 4m-2.107-1.724L11.11 12L16 16v5M9.004 10.276L5 7L3.5 8l3.846 4m0 0L3.5 16L5 17l4.004-3.276M7.346 12l1.658 1.724"
      />
    </Svg>
  );
}
