// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: wallet-2-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Wallet2Line({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M12 7c-4 0-8 3.5-8 8s3.5 6 8 6s8-1.5 8-6s-4-8-8-8Zm0 0c-1.657 0-4-1-4-2.286C8 3.43 10.343 3 12 3s4 .429 4 1.714C16 6 13.657 7 12 7Zm-1.5 4.5l1.5 3l1.5-3M10 14h4m-4 2.5h4M12 14v4"
      />
    </Svg>
  );
}
