// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: wallet-3-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function Wallet3Line({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath fill={color} d="M16 13.5a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0" />
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M4 6.5V18a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1V9a1 1 0 0 0-1-1H5.5A1.5 1.5 0 0 1 4 6.5m0 0A1.5 1.5 0 0 1 5.5 5H16m0 8.5a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0"
      />
    </Svg>
  );
}
