// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: warm-up-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function WarmUpLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M11 16h5.5a.5.5 0 0 1 .5.5V21M12 9l-4.715 2.572a.5.5 0 0 0-.009.873l3.318 1.899M12 9a1 1 0 0 1 1 1v5h-2v-5a1 1 0 0 1 1-1M5 21l3.836-1.917a.5.5 0 0 0 .236-.25L10.715 15M14 5a2 2 0 1 1-4 0a2 2 0 0 1 4 0"
      />
    </Svg>
  );
}
