// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: webhook-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function WebhookLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeWidth="2"
        d="M13.912 9.312a3 3 0 1 0-3.824-4.624a3 3 0 0 0 3.824 4.624Zm-3.824 0l-2.858 4.95m6.682-4.95l2.858 4.95M8.83 18a3 3 0 1 0-5.66-2a3 3 0 0 0 5.66 2Zm0 0h6.34m1.6-3.737a3 3 0 1 0 2.46 5.473a3 3 0 0 0-2.46-5.473Z"
      />
    </Svg>
  );
}
