// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: webhook-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function WebhookFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M15.153 9.461a4 4 0 1 0-6.306 0l-2.085 3.611A4 4 0 1 0 9.465 19h5.07a4 4 0 1 0 2.703-5.927zm.275 4.476l-1.876-3.25A4 4 0 0 1 12 11a4 4 0 0 1-1.552-.312l-1.876 3.249A4 4 0 0 1 10 17h4c0-1.23.555-2.33 1.428-3.063"
        clipRule="evenodd"
      />
    </Svg>
  );
}
