// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: wechat-miniprogram-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function WechatMiniprogramLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="m15.035 12l.09-.036a2.092 2.092 0 0 0-1.188-3.993l-.1.02A2.284 2.284 0 0 0 12 10.23v3.539a2.284 2.284 0 0 1-1.836 2.24l-.101.02a2.092 2.092 0 0 1-1.187-3.994L8.965 12M21 12a9 9 0 1 1-18 0a9 9 0 0 1 18 0"
      />
    </Svg>
  );
}
