// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: wheelchair-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function WheelchairLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M3 3h1.165a1 1 0 0 1 .984.821l1.347 7.409A5 5 0 0 1 8 11m13 5h-1l-2-2h-5.416A5 5 0 0 0 8 11m0 0a5 5 0 1 0 0 10a5 5 0 0 0 0-10m10 7a1.5 1.5 0 1 0 0 3a1.5 1.5 0 0 0 0-3m0 0l-.835-9.181A2 2 0 0 0 15.174 7H6"
      />
    </Svg>
  );
}
