// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: wifi-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function WifiFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="3"
        d="M12 18h.01m-2.839-2.828A4 4 0 0 1 12 14c1.104 0 2.104.448 2.828 1.172m-8.485-2.829A7.98 7.98 0 0 1 12 10c2.209 0 4.209.895 5.657 2.343M3.515 9.515A11.96 11.96 0 0 1 12 6c3.314 0 6.314 1.343 8.485 3.515"
      />
    </Svg>
  );
}
