// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: wind-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function WindLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeWidth="2"
        d="M3 12h15.5a2.5 2.5 0 1 0-2.45-3M5 8h5.5a2.5 2.5 0 1 0-2.45-3M8 16h6.5a2.5 2.5 0 1 1-2.45 3"
      />
    </Svg>
  );
}
