// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: wine-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function WineLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M12 15h5M9.598 9.268l-1.707 1.138A2 2 0 0 0 7 12.07V19a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2v-6.93a2 2 0 0 0-.89-1.664l-1.708-1.138a1 1 0 0 1-.442-.75l-.384-4.601A1 1 0 0 0 12.58 3h-1.16a1 1 0 0 0-.996.917l-.384 4.602a1 1 0 0 1-.442.749"
      />
    </Svg>
  );
}
