// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: wineglass-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function WineglassFill({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        fillRule="evenodd"
        d="M5.847 3.55A2 2 0 0 1 7.796 2h8.409a2 2 0 0 1 1.948 1.55l1.023 4.43c.988 4.283-1.96 8.386-6.176 8.953V20h2a1 1 0 1 1 0 2H9a1 1 0 1 1 0-2h2v-3.067c-4.216-.567-7.164-4.67-6.176-8.953z"
        clipRule="evenodd"
      />
    </Svg>
  );
}
