// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: wiper-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function WiperFill({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill={color}
        d="M12 4c3.355 0 5.716.517 7.266 1.056c1.91.664 2.145.992 2.359 1.163c.337.27.463.728.311 1.133l-3 8a1.01 1.01 0 0 1-1.256.595c-1.741-.565-3.615-.917-5.448-.945l.445 1.661A1.498 1.498 0 0 1 12 19.5a1.5 1.5 0 0 1-1.254-2.32l-.815-3.04a17 17 0 0 1 2.032-.14l-1.326-4.952a1 1 0 0 0-1.931.517l1.483 5.54c-1.308.146-2.61.437-3.847.835l-.02.007l-.005.001a1 1 0 0 1-1.252-.596l-3-8a1 1 0 0 1 .311-1.133c.677-.541 1.553-.883 2.359-1.163C6.284 4.516 8.646 4 12 4"
      />
    </Svg>
  );
}
