// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: world-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function WorldLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeWidth="2"
        d="M19.987 7.5A13.94 13.94 0 0 1 12 10c-2.969 0-5.721-.924-7.987-2.5M21 13.425A16.9 16.9 0 0 1 12 16a16.9 16.9 0 0 1-9-2.575M21 12a9 9 0 1 1-18 0a9 9 0 0 1 18 0Z"
      />
    </Svg>
  );
}
