// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: xbox-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function XboxLine({ size = 24, color: colorProp, style, accessibilityLabel, testID, ...props }: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeWidth="2"
        d="M19.1 18C16.512 12.538 13.09 7.784 7.28 4.257M4.9 18c2.59-5.462 6.01-10.216 11.82-13.743M21 12a9 9 0 1 1-18 0a9 9 0 0 1 18 0Z"
      />
    </Svg>
  );
}
