// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: y-skew-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function YSkewLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeWidth="2"
        d="M6.793 5.725A1 1 0 0 1 7.754 5h8.492a1 1 0 0 1 .961.725l3.61 12.638a.5.5 0 0 1-.48.637H3.663a.5.5 0 0 1-.48-.637z"
      />
    </Svg>
  );
}
