// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: za-sort-descending-letters-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function ZaSortDescendingLettersLine({ size = 24, color: colorProp, style, accessibilityLabel, testID }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M17 5v14.828M19.828 17L17 19.828L14.172 17m-8.458 1h4.572M5 20l2.381-6.668A.5.5 0 0 1 7.852 13h.296a.5.5 0 0 1 .47.332L11 20M5 4h6l-6 6h6"
      />
    </Svg>
  );
}
