// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: za-sort-ascending-letters-line · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import { useThemeColor } from 'rn-motion-ui/theme/use-theme-color';
import type { IconProps } from '../icon-props';

export function ZaSortAscendingLettersLine({ size = 24, color: colorProp, style, accessibilityLabel }: IconProps) {
  const defaultColor = useThemeColor('foreground');
  const color = colorProp ?? defaultColor;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M17 20V5.328m-2.828 2.5L17 5l2.828 2.828M6 18h4m-5 2l2.332-6.53a.71.71 0 0 1 1.336 0L11 20M5 4h5.759a.1.1 0 0 1 .07.17L5.171 9.83a.1.1 0 0 0 .07.17H11"
      />
    </Svg>
  );
}
