// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// mingcute icon: za-sort-descending-letters-fill · @iconify-json/mingcute v1.2.8
import { Svg, Path as SvgPath } from 'react-native-svg';
import type { IconProps } from '../icon-props';
import { useIconColor } from '../resolve-icon-color';

export function ZaSortDescendingLettersFill({
  size = 24,
  color: colorProp,
  style,
  accessibilityLabel,
  testID,
  ...props
}: IconProps) {
  const color = useIconColor(colorProp);
  return (
    <Svg
      {...props}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      color={color}
      style={style}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      <SvgPath
        fill="none"
        stroke={color}
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="3"
        d="M17 5v14.828M19.828 17L17 19.828L14.172 17m-8.636 2h4.928M5 20.5l2.381-6.668a.5.5 0 0 1 .471-.332h.296a.5.5 0 0 1 .47.332L11 20.5m-6-17h6l-6 6h6"
      />
    </Svg>
  );
}
